const Destination = require('../models/Destination');

const hillStationDestinations = [
  // =========================================================================
  // 1. SHIMLA, HIMACHAL PRADESH (8 ICONIC PLACES)
  // =========================================================================
  {
    title: 'The Ridge, Shimla',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Shimla',
    category: 'Hill Stations',
    description: 'The wide open-air cultural and public promenade overlooking the snow-crested Dhauladhar and Pir Panjal mountain ranges. Vehicle-free with neo-Gothic Christ Church and direct pedestrian links to Mall Road and Lakkar Bazaar.',
    shortDescription: 'The heart of Shimla with colonial vistas, pedestrian concourse, and panoramic Himalayan views.',
    images: [
      'https://images.unsplash.com/photo-1597074866923-dc0589150458?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 31.1048, lng: 77.1734, address: 'The Ridge, Center Mall, Shimla, Himachal Pradesh 171001' },
    crowdStatus: 'moderate',
    crowdPercentage: 62,
    rating: 4.8,
    numReviews: 245,
    isPopular: true,
    entryFee: 'Free entry',
    timings: 'Open 24 hours (Peak hours 04:00 PM - 09:00 PM)',
    bestTimeToVisit: 'March to June, November to February for snowfall',
    emergencyHelpline: '112 / DDMA Shimla 1077 / Police 0177-2803211',
    tags: ['Hill Station', 'Shimla', 'Himachal Pradesh', 'The Ridge', 'Colonial', 'Scenic'],
  },
  {
    title: 'Mall Road & Gaiety Theatre Heritage Zone',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Shimla',
    category: 'Shopping Areas',
    description: 'Historic pedestrian-only promenade lined with colonial buildings, local Himachali wool shops, traditional cafes, and the Victorian Gaiety Heritage Cultural Complex established in 1887.',
    shortDescription: 'Shimla’s vibrant pedestrian boulevard known for heritage architecture, cafes, and winter shopping.',
    images: [
      'https://images.unsplash.com/photo-1597074866923-dc0589150458?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 31.1041, lng: 77.1709, address: 'Mall Road, Shimla, Himachal Pradesh 171001' },
    crowdStatus: 'high',
    crowdPercentage: 78,
    rating: 4.7,
    numReviews: 310,
    isPopular: true,
    entryFee: 'Free (Gaiety Theatre ₹25)',
    timings: '09:00 AM - 10:00 PM',
    bestTimeToVisit: 'Throughout the year',
    emergencyHelpline: '112 / Shimla Mall Police 0177-2803211',
    tags: ['Hill Station', 'Shimla', 'Himachal Pradesh', 'Mall Road', 'Heritage', 'Shopping Areas'],
  },
  {
    title: 'Jakhoo Temple & Giant Hanuman Statue',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Shimla',
    category: 'Temples',
    description: 'Perched on Jakhoo Hill, the highest peak in Shimla at 2,455 meters, this revered ancient shrine features a colossal 108-foot Lord Hanuman statue visible from almost anywhere across the hill station.',
    shortDescription: 'Highest Himalayan vantage point in Shimla with a 108-ft Hanuman statue and cable car access.',
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1597074866923-dc0589150458?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 31.1012, lng: 77.1842, address: 'Jakhoo Hill, Shimla, Himachal Pradesh 171001' },
    crowdStatus: 'moderate',
    crowdPercentage: 55,
    rating: 4.7,
    numReviews: 198,
    isPopular: true,
    entryFee: 'Free (Ropeway ticket ~₹550 return)',
    timings: '06:00 AM - 08:00 PM',
    bestTimeToVisit: 'March to June, September to November',
    emergencyHelpline: '112 / Jakhoo Ropeway Aid 0177-2652150',
    tags: ['Hill Station', 'Shimla', 'Himachal Pradesh', 'Temples', 'Ropeway', 'High Altitude'],
  },
  {
    title: 'Christ Church & Lakkar Bazaar Ridge Trail',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Shimla',
    category: 'Historical Places',
    description: 'North India’s second oldest church built in 1857 in neo-Gothic style, famed for its five stained glass windows. Adjacent to Lakkar Bazaar, famous for handcrafted walnut woodwork and walking sticks.',
    shortDescription: 'Iconic 1857 neo-Gothic landmark church with stained glass windows and walnut wood artisan market.',
    images: [
      'https://images.unsplash.com/photo-1597074866923-dc0589150458?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 31.1054, lng: 77.1748, address: 'The Ridge, Lakkar Bazaar, Shimla, Himachal Pradesh 171001' },
    crowdStatus: 'moderate',
    crowdPercentage: 48,
    rating: 4.8,
    numReviews: 175,
    isPopular: true,
    entryFee: 'Free entry',
    timings: '08:00 AM - 06:00 PM',
    bestTimeToVisit: 'October to May',
    emergencyHelpline: '112 / Tourism Info 1363',
    tags: ['Hill Station', 'Shimla', 'Himachal Pradesh', 'Historical Places', 'Handicrafts'],
  },
  {
    title: 'Kufri Fun World & Mahasu Peak',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Shimla',
    category: 'Tourist Places',
    description: 'Situated at 2,720m, Kufri is the winter sports and snow capital of Shimla district, featuring yak rides, Go-Karting on one of the world highest tracks, and Himalayan Nature Park.',
    shortDescription: 'High-altitude snow playground and nature park offering horse trails, skiing, and Himalayan wildlife.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 31.0979, lng: 77.2677, address: 'Mahasu Ridge, Kufri, Shimla, Himachal Pradesh 171012' },
    crowdStatus: 'high',
    crowdPercentage: 74,
    rating: 4.6,
    numReviews: 220,
    isPopular: true,
    entryFee: 'Park entry ₹50, rides separate',
    timings: '09:00 AM - 06:00 PM',
    bestTimeToVisit: 'December to February for snow; April to June for scenic coolness',
    emergencyHelpline: '112 / Kufri Police Post 0177-2740233',
    tags: ['Hill Station', 'Shimla', 'Himachal Pradesh', 'Kufri', 'Snow', 'Adventure'],
  },
  {
    title: 'Tara Devi Temple Hill Top',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Shimla',
    category: 'Temples',
    description: 'Set amidst dense pine and rhododendron forests on a secluded mountain peak 11 km from central Shimla, offering tranquil panoramic vistas of the surrounding valleys and sacred shrines.',
    shortDescription: 'Serene 250-year-old hilltop sanctum offering 360-degree valley views and pine forest trails.',
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 31.0664, lng: 77.1352, address: 'Tara Devi Peak, Shimla, Himachal Pradesh 171010' },
    crowdStatus: 'low',
    crowdPercentage: 30,
    rating: 4.9,
    numReviews: 140,
    isPopular: false,
    entryFee: 'Free entry',
    timings: '07:00 AM - 06:30 PM',
    bestTimeToVisit: 'March to November',
    emergencyHelpline: '112 / Shimla Rural Police 0177-2831211',
    tags: ['Hill Station', 'Shimla', 'Himachal Pradesh', 'Temples', 'Serene', 'Pine Forests'],
  },
  {
    title: 'Viceregal Lodge & Observatory Hill',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Shimla',
    category: 'Historical Places',
    description: 'Also known as Rashtrapati Niwas, this magnificent English Renaissance mansion was the summer residence of the British Viceroy. Today it houses the Indian Institute of Advanced Study with manicured botanical lawns.',
    shortDescription: 'Victorian English Renaissance architectural masterpiece with historic conference rooms and arboretum.',
    images: [
      'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 31.1039, lng: 77.1408, address: 'Observatory Hill, Boileauganj, Shimla, Himachal Pradesh 171005' },
    crowdStatus: 'low',
    crowdPercentage: 35,
    rating: 4.8,
    numReviews: 180,
    isPopular: true,
    entryFee: '₹40 (Indians), ₹85 for internal tour',
    timings: '10:00 AM - 05:00 PM (Closed on Mondays)',
    bestTimeToVisit: 'March to June, September to December',
    emergencyHelpline: '112 / IIAS Administration 0177-2831375',
    tags: ['Hill Station', 'Shimla', 'Himachal Pradesh', 'Historical Places', 'Architecture'],
  },
  {
    title: 'Chadwick Falls & Glen Forest Valley',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Shimla',
    category: 'Tourist Places',
    description: 'A 67-meter crystal-clear waterfall tumbling into a gorge encircled by thick deodar and pine trees in the Glen nature corridor. Ideal for nature walks and photography.',
    shortDescription: 'Cascade framed by deodar forest canopy and serene forest stream trails.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 31.1158, lng: 77.1384, address: 'Glen Forest, Summer Hill, Shimla, Himachal Pradesh 171005' },
    crowdStatus: 'low',
    crowdPercentage: 25,
    rating: 4.6,
    numReviews: 110,
    isPopular: false,
    entryFee: 'Free entry',
    timings: '06:00 AM - 06:00 PM',
    bestTimeToVisit: 'July to October (post-monsoon for maximum flow)',
    emergencyHelpline: '112 / Summer Hill Post 0177-2831200',
    tags: ['Hill Station', 'Shimla', 'Himachal Pradesh', 'Waterfall', 'Nature'],
  },

  // =========================================================================
  // 2. MANALI, HIMACHAL PRADESH (8 ICONIC PLACES)
  // =========================================================================
  {
    title: 'Solang Valley Adventure Grounds',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Manali',
    category: 'Hill Stations',
    description: 'Famous valley nestled between Solang village and Beas Kund, celebrated for year-round adventure: paragliding, zorbing, quad biking, ropeways in summer, and alpine skiing in winter.',
    shortDescription: 'Manali’s premiere adventure paradise offering paragliding, cable car rides, and winter ski slopes.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1597074866923-dc0589150458?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 32.3166, lng: 77.1578, address: 'Solang Valley, Burwa, Manali, Himachal Pradesh 175131' },
    crowdStatus: 'high',
    crowdPercentage: 82,
    rating: 4.8,
    numReviews: 290,
    isPopular: true,
    entryFee: 'Free entry; activities individually ticketed',
    timings: '09:00 AM - 06:00 PM',
    bestTimeToVisit: 'December to February for snow; April to June for paragliding',
    emergencyHelpline: '112 / Manali Tourist Police 01902-252322',
    tags: ['Hill Station', 'Manali', 'Himachal Pradesh', 'Adventure', 'Paragliding', 'Skiing'],
  },
  {
    title: 'Rohtang Pass Snow Crest & Glacial Vantage',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Manali',
    category: 'Tourist Places',
    description: 'Legendary high mountain pass at 3,978 meters connecting Kullu Valley with Lahaul and Spiti. Offers majestic glacial panoramas, permanent snowfields, and dramatic Pir Panjal topography.',
    shortDescription: 'World-famous 3,978m mountain pass with polar snowscapes, glaciers, and NGT e-permit access.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 32.3716, lng: 77.2466, address: 'Rohtang Pass Highway, Manali, Himachal Pradesh 175131' },
    crowdStatus: 'moderate',
    crowdPercentage: 60,
    rating: 4.9,
    numReviews: 340,
    isPopular: true,
    entryFee: 'NGT Permit ₹550 per vehicle',
    timings: '06:00 AM - 04:00 PM (Closed on Tuesdays for road maintenance)',
    bestTimeToVisit: 'June to October (subject to snow clearance)',
    emergencyHelpline: '112 / BRO Rohtang Rescue Post / 01902-252322',
    tags: ['Hill Station', 'Manali', 'Himachal Pradesh', 'Rohtang', 'Glaciers', 'High Altitude'],
  },
  {
    title: 'Hadimba Devi Ancient Cedar Temple',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Manali',
    category: 'Temples',
    description: 'Unique four-tiered wooden pagoda temple built in 1553 AD by Maharaja Bahadur Singh in the heart of the Dhungri deodar forest, dedicated to Goddess Hadimba from the Mahabharata.',
    shortDescription: '16th-century wooden pagoda temple tucked inside a sacred ancient Himalayan deodar forest.',
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 32.2483, lng: 77.1808, address: 'Dhungri Van Vihar, Manali, Himachal Pradesh 175131' },
    crowdStatus: 'moderate',
    crowdPercentage: 58,
    rating: 4.7,
    numReviews: 260,
    isPopular: true,
    entryFee: 'Free entry',
    timings: '08:00 AM - 06:00 PM',
    bestTimeToVisit: 'All year round',
    emergencyHelpline: '112 / Dhungri Tourist Post 01902-252114',
    tags: ['Hill Station', 'Manali', 'Himachal Pradesh', 'Temples', 'Heritage', 'Cedar Forest'],
  },
  {
    title: 'Old Manali Village & Riverside Cafes',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Manali',
    category: 'Cafes & Restaurants',
    description: 'Charming traditional Himachali village across the Manalsu River, known for wood-and-stone Kathkuni houses, apple orchards, live acoustic music cafes, and artisan craft shops.',
    shortDescription: 'Bohemian mountain hamlet with riverside cafes, acoustic music, and traditional wooden architecture.',
    images: [
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 32.2568, lng: 77.1793, address: 'Old Manali Village, Manali, Himachal Pradesh 175131' },
    crowdStatus: 'moderate',
    crowdPercentage: 45,
    rating: 4.8,
    numReviews: 190,
    isPopular: true,
    entryFee: 'Free entry',
    timings: 'Open daily 10:00 AM - 11:00 PM',
    bestTimeToVisit: 'April to June, September to November',
    emergencyHelpline: '112 / Manali Police 01902-252322',
    tags: ['Hill Station', 'Manali', 'Himachal Pradesh', 'Cafes & Restaurants', 'Old Towns'],
  },
  {
    title: 'Vashisht Hot Water Sulphur Springs & Temple',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Manali',
    category: 'Temples',
    description: 'Ancient village perched above the Beas River containing 4,000-year-old shrines dedicated to sage Vashishta, featuring natural therapeutic hot sulphur water springs with separate bathing Kunds.',
    shortDescription: 'Sacred mountain village famous for natural medicinal sulphur hot springs and wooden temples.',
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 32.2625, lng: 77.1972, address: 'Vashisht Village, Manali, Himachal Pradesh 175131' },
    crowdStatus: 'low',
    crowdPercentage: 35,
    rating: 4.6,
    numReviews: 165,
    isPopular: true,
    entryFee: 'Free entry',
    timings: '07:00 AM - 01:00 PM, 02:00 PM - 09:00 PM',
    bestTimeToVisit: 'October to May',
    emergencyHelpline: '112 / Vashisht Panchayat Post',
    tags: ['Hill Station', 'Manali', 'Himachal Pradesh', 'Temples', 'Hot Springs', 'Wellness'],
  },
  {
    title: 'Jogini Waterfall Forest Trail',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Manali',
    category: 'Tourist Places',
    description: 'Enchanting 160-foot cascading stream cascading down from cliff tops into the Beas River basin. Reached via a gentle 45-minute pine-fringed trek starting from Vashisht village.',
    shortDescription: 'Scenic 160-ft waterfall reached via a scenic pine forest trek with mountain stream crossings.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 32.2742, lng: 77.1994, address: 'Jogini Waterfall Trail, Vashisht, Manali, Himachal Pradesh 175131' },
    crowdStatus: 'low',
    crowdPercentage: 28,
    rating: 4.8,
    numReviews: 185,
    isPopular: true,
    entryFee: 'Free entry',
    timings: '06:00 AM - 05:30 PM (Daylight only)',
    bestTimeToVisit: 'March to June, September to November',
    emergencyHelpline: '112 / Mountain Rescue Manali',
    tags: ['Hill Station', 'Manali', 'Himachal Pradesh', 'Waterfall', 'Trekking', 'Nature'],
  },
  {
    title: 'Mall Road Manali & Tibetan Monastery',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Manali',
    category: 'Shopping Areas',
    description: 'The bustling town center of Manali, packed with Kashmiri shawl stores, Kullu cap emporiums, Tibetan monasteries with prayer wheels, and authentic Himachali trout restaurants.',
    shortDescription: 'Central pedestrian thoroughfare featuring Tibetan monasteries, Kullu shawls, and food markets.',
    images: [
      'https://images.unsplash.com/photo-1597074866923-dc0589150458?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 32.2396, lng: 77.1887, address: 'Mall Road, Siyal, Manali, Himachal Pradesh 175131' },
    crowdStatus: 'high',
    crowdPercentage: 80,
    rating: 4.6,
    numReviews: 270,
    isPopular: true,
    entryFee: 'Free entry',
    timings: '09:00 AM - 10:30 PM',
    bestTimeToVisit: 'Throughout the year',
    emergencyHelpline: '112 / Manali City Police 01902-252322',
    tags: ['Hill Station', 'Manali', 'Himachal Pradesh', 'Shopping Areas', 'Tibetan'],
  },
  {
    title: 'Atal Tunnel North & South Portals (Sissu Link)',
    country: 'India',
    state: 'Himachal Pradesh',
    city: 'Manali',
    category: 'Tourist Places',
    description: 'The world’s longest highway tunnel above 10,000 feet (9.02 km) cutting through the Pir Panjal range. Emerges from verdant Manali into the breathtaking Martian-like high-altitude valley of Sissu, Lahaul.',
    shortDescription: 'World-record 9.02km engineering marvel connecting lush Kullu with the stark beauty of Lahaul Valley.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 32.3644, lng: 77.1328, address: 'Atal Tunnel South Portal, Dhundi, Himachal Pradesh 175140' },
    crowdStatus: 'moderate',
    crowdPercentage: 52,
    rating: 4.9,
    numReviews: 320,
    isPopular: true,
    entryFee: 'Free vehicular toll',
    timings: 'Open 24 hours (Subject to weather check)',
    bestTimeToVisit: 'All year round',
    emergencyHelpline: '112 / BRO Tunnel Control Room / 01902-252000',
    tags: ['Hill Station', 'Manali', 'Himachal Pradesh', 'Atal Tunnel', 'Lahaul', 'Engineering'],
  },

  // =========================================================================
  // 3. MUSSOORIE, UTTARAKHAND (8 ICONIC PLACES)
  // =========================================================================
  {
    title: 'Kempty Falls Cascade & Stream',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Mussoorie',
    category: 'Hill Stations',
    description: 'Renowned 40-foot mountain cascade cascading through rock cliffs into a large natural swimming pool, surrounded by high Himalayan ranges. Includes ropeway cable car access.',
    shortDescription: 'Mussoorie’s iconic waterfall cascade with a natural plunge pool and mountain cable car.',
    images: [
      'https://images.unsplash.com/photo-1625057488410-22f7e1b4cce4?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.4852, lng: 78.0287, address: 'Lakhwad, Kempty, Mussoorie, Uttarakhand 248179' },
    crowdStatus: 'high',
    crowdPercentage: 85,
    rating: 4.7,
    numReviews: 280,
    isPopular: true,
    entryFee: 'Free entry (Ropeway ₹150)',
    timings: '08:00 AM - 05:30 PM',
    bestTimeToVisit: 'March to June, September to November',
    emergencyHelpline: '112 / Mussoorie Police 0135-2632003 / DDMA 1077',
    tags: ['Hill Station', 'Mussoorie', 'Uttarakhand', 'Waterfall', 'Scenic'],
  },
  {
    title: 'Mall Road Mussoorie & Library Chowk',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Mussoorie',
    category: 'Shopping Areas',
    description: 'A vibrant 2-km colonial ridge walking boulevard stretching between Library Chowk and Picture Palace. Lined with lampposts, antique benches, bakeries, wooden curio shops, and Doon Valley vistas.',
    shortDescription: 'Colonial ridge promenade offering Doon Valley lights, famous bakeries, and heritage bookshops.',
    images: [
      'https://images.unsplash.com/photo-1625057488410-22f7e1b4cce4?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.4578, lng: 78.0747, address: 'The Mall Road, Mussoorie, Uttarakhand 248179' },
    crowdStatus: 'high',
    crowdPercentage: 76,
    rating: 4.7,
    numReviews: 240,
    isPopular: true,
    entryFee: 'Free entry (Vehicular barrier ₹150 for cars)',
    timings: '09:00 AM - 10:00 PM',
    bestTimeToVisit: 'April to June, October to February',
    emergencyHelpline: '112 / Library Chowk Post 0135-2632003',
    tags: ['Hill Station', 'Mussoorie', 'Uttarakhand', 'Mall Road', 'Shopping Areas'],
  },
  {
    title: 'Gun Hill Cable Car & Panoramic Viewpoint',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Mussoorie',
    category: 'Tourist Places',
    description: 'The second highest point in Mussoorie at 2,024m. Historical site where a mid-day cannon was fired during British times. Accessible via an exhilarating 400m aerial ropeway.',
    shortDescription: 'Second highest peak reached via aerial ropeway, boasting 360-degree views of Himalayan snow peaks.',
    images: [
      'https://images.unsplash.com/photo-1625057488410-22f7e1b4cce4?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.4608, lng: 78.0772, address: 'Gun Hill, Mall Road, Mussoorie, Uttarakhand 248179' },
    crowdStatus: 'moderate',
    crowdPercentage: 65,
    rating: 4.6,
    numReviews: 210,
    isPopular: true,
    entryFee: 'Ropeway ride ₹125 return',
    timings: '10:00 AM - 06:00 PM',
    bestTimeToVisit: 'All year round (Clear views in autumn)',
    emergencyHelpline: '112 / Ropeway Control 0135-2632003',
    tags: ['Hill Station', 'Mussoorie', 'Uttarakhand', 'Ropeway', 'Himalayas'],
  },
  {
    title: 'Camel’s Back Road Nature Trail',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Mussoorie',
    category: 'Tourist Places',
    description: 'A 3-km peaceful walking track resembling a camel’s hump. Known for its tranquil pine-covered trail, morning jogger views of the Badrinath and Kedarnath peaks, and old British cemetery.',
    shortDescription: 'Peaceful 3km scenic ridge trail named after natural camel-shaped rock formations.',
    images: [
      'https://images.unsplash.com/photo-1625057488410-22f7e1b4cce4?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.4619, lng: 78.0798, address: 'Camel\'s Back Road, Mussoorie, Uttarakhand 248179' },
    crowdStatus: 'low',
    crowdPercentage: 30,
    rating: 4.8,
    numReviews: 170,
    isPopular: false,
    entryFee: 'Free entry',
    timings: 'Open 24 hours (Best during sunrise/sunset)',
    bestTimeToVisit: 'Throughout the year',
    emergencyHelpline: '112 / Mussoorie Tourist Help 1363',
    tags: ['Hill Station', 'Mussoorie', 'Uttarakhand', 'Nature Trail', 'Sunset'],
  },
  {
    title: 'George Everest’s House & Observatory Peak',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Mussoorie',
    category: 'Historical Places',
    description: 'Historic 1832 estate and laboratory of Sir George Everest, Surveyor General of India after whom Mount Everest was named. Features dramatic cliff-edge views of the Doon Valley on one side and Aglar River on the other.',
    shortDescription: 'Historic 1832 estate of the Surveyor General perched on a scenic ridge overlooking Doon Valley.',
    images: [
      'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.4593, lng: 78.0251, address: 'Park Estate, Hathipaon, Mussoorie, Uttarakhand 248179' },
    crowdStatus: 'moderate',
    crowdPercentage: 42,
    rating: 4.9,
    numReviews: 195,
    isPopular: true,
    entryFee: '₹20 heritage museum entry',
    timings: '09:00 AM - 06:00 PM',
    bestTimeToVisit: 'October to April',
    emergencyHelpline: '112 / Forest Guard Hathipaon',
    tags: ['Hill Station', 'Mussoorie', 'Uttarakhand', 'Historical Places', 'Heritage'],
  },
  {
    title: 'Lal Tibba Scenic Point Landour',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Mussoorie',
    category: 'Tourist Places',
    description: 'The highest point in Mussoorie-Landour at 2,275 meters. Features mounted telescopes on a vintage wooden cafe rooftop to gaze upon Nilkantha, Swargarohini, and Bandarpunch peaks.',
    shortDescription: 'Highest vantage point in Landour with telescope roof deck viewing snow-capped Garhwal peaks.',
    images: [
      'https://images.unsplash.com/photo-1625057488410-22f7e1b4cce4?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.4632, lng: 78.1065, address: 'Upper Mall Road, Landour, Mussoorie, Uttarakhand 248179' },
    crowdStatus: 'moderate',
    crowdPercentage: 50,
    rating: 4.8,
    numReviews: 220,
    isPopular: true,
    entryFee: '₹50 (inclusive of telescope view)',
    timings: '06:00 AM - 07:00 PM',
    bestTimeToVisit: 'October to March for crisp crystal-clear visibility',
    emergencyHelpline: '112 / Landour Cantonment Board Police',
    tags: ['Hill Station', 'Mussoorie', 'Uttarakhand', 'Landour', 'Viewpoint'],
  },
  {
    title: 'Cloud’s End Heritage Forest Frontier',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Mussoorie',
    category: 'Tourist Places',
    description: 'Marks the geographical end of the Mussoorie hill town, enveloped in 2,000 acres of dense oak and deodar wilderness. Built in 1838, it is one of the earliest British bungalows in Garhwal.',
    shortDescription: 'Pristine 2,000-acre virgin oak and deodar forest marking the tranquil western frontier of Mussoorie.',
    images: [
      'https://images.unsplash.com/photo-1625057488410-22f7e1b4cce4?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.4655, lng: 78.0068, address: 'Cloud\'s End Forest Reserve, Hathipaon, Uttarakhand 248179' },
    crowdStatus: 'low',
    crowdPercentage: 20,
    rating: 4.8,
    numReviews: 95,
    isPopular: false,
    entryFee: '₹50 entry per person',
    timings: '08:00 AM - 06:00 PM',
    bestTimeToVisit: 'March to June, September to December',
    emergencyHelpline: '112 / Forest Division Mussoorie',
    tags: ['Hill Station', 'Mussoorie', 'Uttarakhand', 'Forest', 'Quiet'],
  },
  {
    title: 'Company Garden & Municipal Flower Park',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Mussoorie',
    category: 'Tourist Places',
    description: 'A beautifully manicured public park maintained by the Garden Welfare Association, featuring lush floral lawns, a central fountain, an artificial waterfall, and an extensive greenhouse of rare Himalayan flora.',
    shortDescription: 'Lush Victorian floral garden with artificial cascade, greenhouse, and family boating pond.',
    images: [
      'https://images.unsplash.com/photo-1625057488410-22f7e1b4cce4?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.4682, lng: 78.0494, address: 'Bazar Road, Landour, Mussoorie, Uttarakhand 248179' },
    crowdStatus: 'low',
    crowdPercentage: 35,
    rating: 4.6,
    numReviews: 150,
    isPopular: true,
    entryFee: '₹25 per adult',
    timings: '09:00 AM - 06:00 PM',
    bestTimeToVisit: 'April to July',
    emergencyHelpline: '112 / Municipal Board Mussoorie',
    tags: ['Hill Station', 'Mussoorie', 'Uttarakhand', 'Gardens', 'Family'],
  },

  // =========================================================================
  // 4. NAINITAL, UTTARAKHAND (7 ICONIC PLACES)
  // =========================================================================
  {
    title: 'Naini Lake & Boat Club Promenade',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Nainital',
    category: 'Hill Stations',
    description: 'The pear-shaped natural freshwater eye of Nainital encircled by seven emerald green mountain peaks. Known for wooden yacht sailing, paddle boating, and romantic evening shoreline strolls.',
    shortDescription: 'The centerpiece emerald eye of Kumaon with rowing boats, yacht sailing, and perimeter promenade.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 29.3919, lng: 79.4542, address: 'Mallital / Tallital Shoreline, Nainital, Uttarakhand 263002' },
    crowdStatus: 'high',
    crowdPercentage: 80,
    rating: 4.8,
    numReviews: 320,
    isPopular: true,
    entryFee: 'Boating ₹210 to ₹420 per round',
    timings: '06:00 AM - 07:00 PM',
    bestTimeToVisit: 'March to June, September to January',
    emergencyHelpline: '112 / DDMA Nainital 1077 / Police 05942-235555',
    tags: ['Hill Station', 'Nainital', 'Uttarakhand', 'Naini Lake', 'Boating', 'Lake District'],
  },
  {
    title: 'Maa Naina Devi Temple & Mallital Shore',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Nainital',
    category: 'Temples',
    description: 'One of the 51 sacred Shakti Peethas situated on the northern bank of Naini Lake where Goddess Sati’s eyes (Naina) are believed to have fallen. Revered pilgrimage site with lakeside brass bells.',
    shortDescription: 'Sacred lakeside Shakti Peetha where Goddess Sati’s eyes are believed to have fallen.',
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 29.3956, lng: 79.4528, address: 'Ayarpattar Hill Base, Mallital, Nainital, Uttarakhand 263002' },
    crowdStatus: 'moderate',
    crowdPercentage: 60,
    rating: 4.9,
    numReviews: 240,
    isPopular: true,
    entryFee: 'Free entry',
    timings: '06:00 AM - 10:00 PM',
    bestTimeToVisit: 'Throughout the year (Nanda Devi Mela in September)',
    emergencyHelpline: '112 / Mallital Police 05942-235455',
    tags: ['Hill Station', 'Nainital', 'Uttarakhand', 'Temples', 'Shakti Peetha'],
  },
  {
    title: 'Snow View Point & Aerial Ropeway',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Nainital',
    category: 'Tourist Places',
    description: 'Located at an elevation of 2,270m, offering grand unobstructed panoramic views of the mighty Himalayan crest including Nanda Devi, Trishul, and Nanda Kot. Accessible via cable car from Mallital.',
    shortDescription: 'Mountaintop vantage point at 2,270m offering binoculars view of Nanda Devi and Trishul crests.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 29.3982, lng: 79.4589, address: 'Sher-Ka-Danda Ridge, Nainital, Uttarakhand 263002' },
    crowdStatus: 'moderate',
    crowdPercentage: 55,
    rating: 4.7,
    numReviews: 210,
    isPopular: true,
    entryFee: 'Ropeway ticket ~₹300 roundtrip',
    timings: '10:00 AM - 05:00 PM',
    bestTimeToVisit: 'October to February for snow and clear Himalayan vistas',
    emergencyHelpline: '112 / Nainital Ropeway Control',
    tags: ['Hill Station', 'Nainital', 'Uttarakhand', 'Ropeway', 'Himalayas'],
  },
  {
    title: 'Mall Road Nainital (Govind Ballabh Pant Marg)',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Nainital',
    category: 'Shopping Areas',
    description: 'The scenic boulevard connecting the twin settlements of Tallital and Mallital running parallel along the entire length of Naini Lake. Famous for handmade decorative wax candles and pine handicrafts.',
    shortDescription: 'Lakeside shopping and evening promenade famous for decorative scented candles and woolen garments.',
    images: [
      'https://images.unsplash.com/photo-1597074866923-dc0589150458?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 29.3875, lng: 79.4601, address: 'Govind Ballabh Pant Marg, Nainital, Uttarakhand 263001' },
    crowdStatus: 'high',
    crowdPercentage: 75,
    rating: 4.7,
    numReviews: 290,
    isPopular: true,
    entryFee: 'Free entry (Vehicle entry restricted between 6-8 PM)',
    timings: '09:00 AM - 10:00 PM',
    bestTimeToVisit: 'All year round',
    emergencyHelpline: '112 / Tallital Police Station 05942-235777',
    tags: ['Hill Station', 'Nainital', 'Uttarakhand', 'Mall Road', 'Shopping Areas'],
  },
  {
    title: 'Tiffin Top (Dorothy’s Seat) Ayarpatta Hill',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Nainital',
    category: 'Tourist Places',
    description: 'A stone picnic bench perched at 2,292m atop Ayarpatta Peak, built in memory of English artist Dorothy Kellet. Offers sweeping panoramic views of the entire Nainital township and Kumaon mountain chains.',
    shortDescription: 'High-altitude 2,292m stone pavilion offering 360-degree views of the lake town and Kumaon ranges.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 29.3842, lng: 79.4447, address: 'Ayarpatta Hill, Nainital, Uttarakhand 263002' },
    crowdStatus: 'low',
    crowdPercentage: 35,
    rating: 4.8,
    numReviews: 180,
    isPopular: true,
    entryFee: 'Free entry (Horse ride ₹500-₹800 optional)',
    timings: '06:00 AM - 06:00 PM',
    bestTimeToVisit: 'March to June, September to December',
    emergencyHelpline: '112 / Forest Patrol Nainital',
    tags: ['Hill Station', 'Nainital', 'Uttarakhand', 'Trekking', 'Vantage Point'],
  },
  {
    title: 'Eco Cave Gardens Sukhatal',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Nainital',
    category: 'Tourist Places',
    description: 'A cluster of six interconnected natural rocky caves named after animals (Tiger Cave, Panther Cave, Bat Cave, etc.), featuring hanging gardens, musical fountains, and educational trails.',
    shortDescription: 'Interconnected subterranean animal-shaped rock caves with winding pathways and children’s gardens.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 29.3967, lng: 79.4442, address: 'Kaladungi Road, Sukhatal, Mallital, Nainital, Uttarakhand 263001' },
    crowdStatus: 'low',
    crowdPercentage: 40,
    rating: 4.6,
    numReviews: 160,
    isPopular: true,
    entryFee: '₹60 (Adults), ₹25 (Children)',
    timings: '09:30 AM - 05:30 PM',
    bestTimeToVisit: 'March to June, September to November',
    emergencyHelpline: '112 / Sukhatal Tourism Desk',
    tags: ['Hill Station', 'Nainital', 'Uttarakhand', 'Caves', 'Adventure'],
  },
  {
    title: 'Pangot & Kilbury Bird Sanctuary Frontier',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Nainital',
    category: 'Tourist Places',
    description: 'Nestled in thick oak, pine, and rhododendron forests 15 km from Nainital, this world-renowned birding paradise is home to over 580 Himalayan bird species, barking deer, and leopards.',
    shortDescription: 'World-renowned Himalayan birding sanctuary nestled in pristine oak and rhododendron forest.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 29.4278, lng: 79.4182, address: 'Kilbury Road, Pangot, Nainital, Uttarakhand 263001' },
    crowdStatus: 'low',
    crowdPercentage: 20,
    rating: 4.9,
    numReviews: 120,
    isPopular: false,
    entryFee: 'Forest permit ₹100',
    timings: '06:00 AM - 05:00 PM',
    bestTimeToVisit: 'October to May for migratory and resident bird sightings',
    emergencyHelpline: '112 / Pangot Forest Checkpost',
    tags: ['Hill Station', 'Nainital', 'Uttarakhand', 'Bird Sanctuary', 'Wilderness'],
  },

  // =========================================================================
  // 5. RISHIKESH, UTTARAKHAND (8 ICONIC PLACES)
  // =========================================================================
  {
    title: 'Laxman Jhula Suspension Bridge & Tapovan',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Rishikesh',
    category: 'Hill Stations',
    description: 'Historic 450-foot iron suspension bridge spanning the sacred emerald Ganga river. Surrounded by vibrant organic cafes, yoga ashrams, bookshops, and temple spires in Tapovan.',
    shortDescription: 'World-famous iconic Ganga suspension bridge surrounded by rooftop cafes and spiritual ashrams.',
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.1348, lng: 78.3302, address: 'Tapovan, Laxman Jhula, Rishikesh, Uttarakhand 249192' },
    crowdStatus: 'high',
    crowdPercentage: 75,
    rating: 4.8,
    numReviews: 310,
    isPopular: true,
    entryFee: 'Free pedestrian access',
    timings: 'Open 24 hours',
    bestTimeToVisit: 'September to April',
    emergencyHelpline: '112 / Muni Ki Reti Police 0135-2430034 / SDRF 1070',
    tags: ['Hill Station', 'Rishikesh', 'Uttarakhand', 'Laxman Jhula', 'Ganges', 'Yoga'],
  },
  {
    title: 'Ram Jhula & Swarg Ashram Spiritual Ghat',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Rishikesh',
    category: 'Temples',
    description: 'Graceful suspension bridge linking Sivananda Nagar with Swarg Ashram. The bustling spiritual hub of Rishikesh lined with Vedic bookstores, sweet shops, and meditation halls.',
    shortDescription: 'Spiritual suspension bridge linking Sivananda Ashram with the ancient riverside hermitages of Swarg Ashram.',
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.1232, lng: 78.3188, address: 'Swarg Ashram, Ram Jhula, Rishikesh, Uttarakhand 249304' },
    crowdStatus: 'high',
    crowdPercentage: 72,
    rating: 4.8,
    numReviews: 290,
    isPopular: true,
    entryFee: 'Free entry (Motorboats ₹15 across river)',
    timings: 'Open 24 hours',
    bestTimeToVisit: 'Throughout the year',
    emergencyHelpline: '112 / Swarg Ashram Post 0135-2440010',
    tags: ['Hill Station', 'Rishikesh', 'Uttarakhand', 'Temples', 'Ram Jhula', 'Spiritual'],
  },
  {
    title: 'Triveni Ghat Maha Ganga Aarti Concourse',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Rishikesh',
    category: 'Temples',
    description: 'The holiest bathing ghat in Rishikesh where three sacred streams (Ganga, Yamuna, Saraswati) spiritually merge. Famous for the mesmerizing daily evening Maha Aarti with brass lamps and Vedic chants.',
    shortDescription: 'Holiest river ghat in Rishikesh celebrated for the grand twilight Maha Ganga Aarti ceremony.',
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.1058, lng: 78.2974, address: 'Mayakund, Triveni Ghat, Rishikesh, Uttarakhand 249201' },
    crowdStatus: 'high',
    crowdPercentage: 88,
    rating: 4.9,
    numReviews: 350,
    isPopular: true,
    entryFee: 'Free entry',
    timings: '05:00 AM - 09:00 PM (Aarti starts at 06:00 PM)',
    bestTimeToVisit: 'All year round',
    emergencyHelpline: '112 / Rishikesh Kotwali 0135-2430012',
    tags: ['Hill Station', 'Rishikesh', 'Uttarakhand', 'Ganga Aarti', 'Temples', 'Pilgrimage'],
  },
  {
    title: 'Parmarth Niketan Ashram & Ganga Riverbank',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Rishikesh',
    category: 'Temples',
    description: 'One of India’s largest yoga ashrams with over 1,000 rooms, manicured gardens, and iconic seated Lord Shiva statue on the water. Hosts the annual International Yoga Festival.',
    shortDescription: 'Famous spiritual retreat center on the holy Ganges bank with world-renowned yoga programs.',
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.1198, lng: 78.3168, address: 'Main Road, Swarg Ashram, Rishikesh, Uttarakhand 249304' },
    crowdStatus: 'moderate',
    crowdPercentage: 54,
    rating: 4.8,
    numReviews: 230,
    isPopular: true,
    entryFee: 'Free entry to ghat',
    timings: '06:00 AM - 08:30 PM',
    bestTimeToVisit: 'October to April',
    emergencyHelpline: '112 / Parmarth Helpdesk 0135-2440077',
    tags: ['Hill Station', 'Rishikesh', 'Uttarakhand', 'Yoga', 'Ashram', 'Spiritual'],
  },
  {
    title: 'Shivpuri White Water Rafting Launch Beach',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Rishikesh',
    category: 'Tourist Places',
    description: 'Located 16 km upstream from Rishikesh, Shivpuri is the capital of Himalayan river rafting in India. Offers Grade III & IV rapids such as Roller Coaster, Golf Course, and Club House.',
    shortDescription: 'India’s premier white-water rafting launching beach with Grade III & IV Ganga rapids.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.1412, lng: 78.3914, address: 'Badrinath Highway, Shivpuri, Rishikesh, Uttarakhand 249192' },
    crowdStatus: 'moderate',
    crowdPercentage: 65,
    rating: 4.9,
    numReviews: 320,
    isPopular: true,
    entryFee: 'Rafting packages ₹600 - ₹1,500',
    timings: '08:00 AM - 04:30 PM (Closed July-August during monsoon floods)',
    bestTimeToVisit: 'Late September to June',
    emergencyHelpline: '112 / River Rafting Association 0135-2430034 / SDRF 1070',
    tags: ['Hill Station', 'Rishikesh', 'Uttarakhand', 'Rafting', 'Adventure', 'White Water'],
  },
  {
    title: 'Neer Garh (Neer Gaddu) Waterfall Trail',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Rishikesh',
    category: 'Tourist Places',
    description: 'A multi-tiered natural jade-turquoise waterfall tumbling down sheer rock formations in the Rajaji National Park buffer zone. Popular for shallow plunge pools and jungle cafe stops.',
    shortDescription: 'Multi-tiered natural jade waterfall cascade with shallow bathing rock pools and forest trek.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.1486, lng: 78.3418, address: 'Neer Garh Waterfall Road, Rishikesh, Uttarakhand 249192' },
    crowdStatus: 'low',
    crowdPercentage: 40,
    rating: 4.7,
    numReviews: 180,
    isPopular: true,
    entryFee: 'Forest entry ₹30',
    timings: '08:00 AM - 05:00 PM',
    bestTimeToVisit: 'October to May',
    emergencyHelpline: '112 / Forest Range Office Rishikesh',
    tags: ['Hill Station', 'Rishikesh', 'Uttarakhand', 'Waterfall', 'Trekking'],
  },
  {
    title: 'The Beatles Ashram (Chaurasi Kutia)',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Rishikesh',
    category: 'Historical Places',
    description: 'Historic ashram of Maharishi Mahesh Yogi where The Beatles stayed in 1968 and composed over 40 songs on the White Album. Features 84 stone meditation caves and iconic graffiti art halls.',
    shortDescription: 'Legendary 1968 Maharishi retreat where The Beatles wrote their White Album songs.',
    images: [
      'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.1132, lng: 78.3122, address: 'Rajaji Tiger Reserve, Swarg Ashram, Rishikesh, Uttarakhand 249304' },
    crowdStatus: 'low',
    crowdPercentage: 35,
    rating: 4.8,
    numReviews: 220,
    isPopular: true,
    entryFee: '₹150 (Indians), ₹600 (Foreigners)',
    timings: '09:00 AM - 04:30 PM',
    bestTimeToVisit: 'October to April',
    emergencyHelpline: '112 / Rajaji Tiger Reserve Checkpost',
    tags: ['Hill Station', 'Rishikesh', 'Uttarakhand', 'The Beatles', 'Historical Places', 'Art'],
  },
  {
    title: 'Vashishta Gufa Meditation Cave By Ganga',
    country: 'India',
    state: 'Uttarakhand',
    city: 'Rishikesh',
    category: 'Temples',
    description: 'A deeply sacred natural subterranean cave on the banks of the turquoise Ganga where Sage Vashishta is believed to have meditated. Known for an oil lamp shrine and profound pin-drop silence.',
    shortDescription: 'Ancient sacred riverside cave where Sage Vashishta meditated, enveloped in sublime silence.',
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 30.1652, lng: 78.4354, address: 'Badrinath Highway, Gular Dogi, Rishikesh, Uttarakhand 249303' },
    crowdStatus: 'low',
    crowdPercentage: 15,
    rating: 4.9,
    numReviews: 140,
    isPopular: false,
    entryFee: 'Free entry',
    timings: '09:00 AM - 12:00 PM, 03:00 PM - 05:30 PM',
    bestTimeToVisit: 'September to May',
    emergencyHelpline: '112 / Swami Purushottamananda Ashram',
    tags: ['Hill Station', 'Rishikesh', 'Uttarakhand', 'Meditation', 'Cave', 'Spiritual'],
  },

  // =========================================================================
  // 6. OOTY, TAMIL NADU (7 ICONIC PLACES)
  // =========================================================================
  {
    title: 'Ooty Lake & Boat House Promenade',
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Ooty',
    category: 'Hill Stations',
    description: 'An expansive 65-acre artificial lake constructed in 1824 by John Sullivan, surrounded by eucalyptus groves and misty Nilgiri hills. Offers pedal boating, motor launches, and mini-train joyrides.',
    shortDescription: 'Historic 1824 Nilgiri lake surrounded by eucalyptus trees, pedal boats, and mini toy trains.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 11.4082, lng: 76.6896, address: 'North Lake Road, Udhagamandalam, Tamil Nadu 643001' },
    crowdStatus: 'high',
    crowdPercentage: 78,
    rating: 4.7,
    numReviews: 280,
    isPopular: true,
    entryFee: 'Entry ₹13; Boating ₹240 - ₹600',
    timings: '09:00 AM - 05:30 PM',
    bestTimeToVisit: 'October to June',
    emergencyHelpline: '112 / Ooty Police 0423-2442222 / DDMA Nilgiris 1077',
    tags: ['Hill Station', 'Ooty', 'Tamil Nadu', 'Ooty Lake', 'Boating', 'Nilgiris'],
  },
  {
    title: 'Government Botanical Garden Ooty',
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Ooty',
    category: 'Tourist Places',
    description: 'Established in 1848 on the lower slopes of Doddabetta Peak, covering 55 acres across six terraced sections. Houses over a thousand species of exotic flora, bonsai, and a 20-million-year-old fossilized tree trunk.',
    shortDescription: 'World-renowned 55-acre terraced botanical garden established in 1848 with ancient fossil tree.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 11.4194, lng: 76.7118, address: 'Vannarapettai, Udhagamandalam, Tamil Nadu 643002' },
    crowdStatus: 'high',
    crowdPercentage: 74,
    rating: 4.8,
    numReviews: 310,
    isPopular: true,
    entryFee: '₹40 (Adults), ₹20 (Children)',
    timings: '07:00 AM - 06:30 PM',
    bestTimeToVisit: 'April to May during Annual Flower Show; September to February',
    emergencyHelpline: '112 / Horticulture Dept Ooty 0423-2442545',
    tags: ['Hill Station', 'Ooty', 'Tamil Nadu', 'Botanical Garden', 'Flower Show'],
  },
  {
    title: 'Doddabetta Peak Nilgiri Vantage Point',
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Ooty',
    category: 'Tourist Places',
    description: 'The highest mountain in the Nilgiri Hills at 2,637 meters, located 9 km from Ooty. Features a government Telescope House offering sweeping vistas of the Coimbatore plains and Mysore plateau.',
    shortDescription: 'Highest mountain peak in Nilgiris at 2,637m with government telescope viewing house.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 11.4011, lng: 76.7369, address: 'Ooty-Kotagiri Road, Doddabetta, Tamil Nadu 643002' },
    crowdStatus: 'moderate',
    crowdPercentage: 62,
    rating: 4.7,
    numReviews: 260,
    isPopular: true,
    entryFee: '₹10 per adult; Telescope ₹10',
    timings: '09:00 AM - 06:00 PM',
    bestTimeToVisit: 'October to May',
    emergencyHelpline: '112 / Forest Check Post Doddabetta',
    tags: ['Hill Station', 'Ooty', 'Tamil Nadu', 'Peak', 'Nilgiris', 'Viewpoint'],
  },
  {
    title: 'Nilgiri Mountain Railway (Toy Train) Heritage Station',
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Ooty',
    category: 'Historical Places',
    description: 'UNESCO World Heritage rack-and-pinion steam railway built in 1908. Winds through 208 curves, 16 tunnels, and 250 bridges across misty tea gardens, oak forests, and ravines.',
    shortDescription: 'UNESCO World Heritage steam rack railway running through Nilgiri ravines and tea estates.',
    images: [
      'https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 11.4042, lng: 76.6974, address: 'Ooty Railway Station, Udhagamandalam, Tamil Nadu 643001' },
    crowdStatus: 'high',
    crowdPercentage: 86,
    rating: 4.9,
    numReviews: 380,
    isPopular: true,
    entryFee: 'First Class ₹205, Second Class ₹30',
    timings: 'Daily departures 09:15 AM & 02:00 PM',
    bestTimeToVisit: 'All year round (Advance booking required)',
    emergencyHelpline: '112 / Southern Railway Inquiry 139',
    tags: ['Hill Station', 'Ooty', 'Tamil Nadu', 'Toy Train', 'UNESCO', 'Heritage'],
  },
  {
    title: 'Pykara Lake & Cascading Waterfalls',
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Ooty',
    category: 'Tourist Places',
    description: 'Sacred river and reservoir of the Toda tribespeople situated 21 km from Ooty. Features pine-rimmed speedboating facilities and two dramatic cascading waterfalls dropping over granite boulders.',
    shortDescription: 'Sacred Toda mountain river reservoir with thrilling speedboat rides and cascading waterfalls.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 11.4938, lng: 76.6022, address: 'Pykara Dam, Naduvattam, Tamil Nadu 643224' },
    crowdStatus: 'low',
    crowdPercentage: 35,
    rating: 4.8,
    numReviews: 190,
    isPopular: true,
    entryFee: 'Boat house entry ₹10; Speedboat ₹800',
    timings: '09:30 AM - 05:00 PM',
    bestTimeToVisit: 'August to January',
    emergencyHelpline: '112 / TTDC Boathouse Pykara 0423-2444266',
    tags: ['Hill Station', 'Ooty', 'Tamil Nadu', 'Waterfall', 'Boating', 'Pykara'],
  },
  {
    title: 'Government Rose Garden Elk Hill',
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Ooty',
    category: 'Tourist Places',
    description: 'One of the largest rose gardens in India situated at 2,200m on the slopes of Elk Hill. Covers 10 acres of curved terraces boasting over 20,000 varieties of hybrid roses.',
    shortDescription: 'Largest rose sanctuary in India with over 20,000 hybrid roses spread across curved terraces.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 11.4069, lng: 76.7142, address: 'Elk Hill Road, Vijayanagaram, Ooty, Tamil Nadu 643001' },
    crowdStatus: 'moderate',
    crowdPercentage: 45,
    rating: 4.7,
    numReviews: 195,
    isPopular: true,
    entryFee: '₹40 (Adults), ₹20 (Children)',
    timings: '08:30 AM - 06:00 PM',
    bestTimeToVisit: 'March to June during peak bloom season',
    emergencyHelpline: '112 / Rose Garden Officer 0423-2442545',
    tags: ['Hill Station', 'Ooty', 'Tamil Nadu', 'Rose Garden', 'Flowers'],
  },
  {
    title: 'Tea Museum & Doddabetta Tea Factory',
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Ooty',
    category: 'Shopping Areas',
    description: 'Situated alongside emerald tea estates overlooking the Nilgiri valley, showcasing the complete orthodox tea manufacturing process from fresh leaf plucking to crushing, plus homemade chocolate making.',
    shortDescription: 'Interactive aromatic tea processing factory offering fresh Nilgiri tea tastings and chocolate workshops.',
    images: [
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 11.4048, lng: 76.7321, address: 'Doddabetta Road, Ooty, Tamil Nadu 643002' },
    crowdStatus: 'moderate',
    crowdPercentage: 55,
    rating: 4.6,
    numReviews: 230,
    isPopular: true,
    entryFee: '₹30 inclusive of factory tour & tea cup',
    timings: '09:00 AM - 06:30 PM',
    bestTimeToVisit: 'Throughout the year',
    emergencyHelpline: '112 / Tea Museum Help 0423-2444588',
    tags: ['Hill Station', 'Ooty', 'Tamil Nadu', 'Tea Estate', 'Factory Tour'],
  },

  // =========================================================================
  // 7. DARJEELING, WEST BENGAL (8 ICONIC PLACES)
  // =========================================================================
  {
    title: 'Tiger Hill Sunrise & Kanchenjunga Viewpoint',
    country: 'India',
    state: 'West Bengal',
    city: 'Darjeeling',
    category: 'Hill Stations',
    description: 'The highest summit in Darjeeling at 2,590 meters, globally renowned for its surreal sunrise spectacle where the twin peaks of Mount Kanchenjunga and Mount Everest are illuminated in dazzling hues of pink and gold.',
    shortDescription: 'Famed 2,590m summit offering world-renowned sunrise over Mount Kanchenjunga and Mount Everest.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 26.9938, lng: 88.2862, address: 'Tiger Hill Observatory, Senchal Forest, Darjeeling, West Bengal 734102' },
    crowdStatus: 'high',
    crowdPercentage: 88,
    rating: 4.9,
    numReviews: 360,
    isPopular: true,
    entryFee: 'Observatory ₹50 per person',
    timings: '04:00 AM - 06:30 AM (Peak morning sunrise hours)',
    bestTimeToVisit: 'October to December, March to April for crisp skies',
    emergencyHelpline: '112 / Darjeeling Police 0354-2254422 / DDMA 1077',
    tags: ['Hill Station', 'Darjeeling', 'West Bengal', 'Tiger Hill', 'Kanchenjunga', 'Sunrise'],
  },
  {
    title: 'Batasia Loop & Gorkha War Memorial',
    country: 'India',
    state: 'West Bengal',
    city: 'Darjeeling',
    category: 'Historical Places',
    description: 'A spiral railway engineering loop where the Darjeeling Himalayan Toy Train wraps 360 degrees around a manicured mountain garden and war memorial honoring valiant Gorkha soldiers, framing Kanchenjunga.',
    shortDescription: 'Historic spiral railway loop garden honoring Gorkha soldiers against Kanchenjunga backdrop.',
    images: [
      'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 27.0169, lng: 88.2474, address: 'Hill Cart Road, Ghoom, Darjeeling, West Bengal 734102' },
    crowdStatus: 'moderate',
    crowdPercentage: 68,
    rating: 4.8,
    numReviews: 290,
    isPopular: true,
    entryFee: 'Garden entry ₹20',
    timings: '05:00 AM - 06:30 PM',
    bestTimeToVisit: 'September to May',
    emergencyHelpline: '112 / Ghoom Police Outpost 0354-2274222',
    tags: ['Hill Station', 'Darjeeling', 'West Bengal', 'Batasia Loop', 'War Memorial', 'Toy Train'],
  },
  {
    title: 'Darjeeling Himalayan Railway (DHR) Heritage Station',
    country: 'India',
    state: 'West Bengal',
    city: 'Darjeeling',
    category: 'Historical Places',
    description: 'UNESCO World Heritage narrow-gauge mountain railway commissioned in 1881. Historic steam-powered locomotives traverse narrow mountain passes, tea slopes, and street markets.',
    shortDescription: '1881 UNESCO narrow-gauge mountain steam railway winding across tea gardens and bazaars.',
    images: [
      'https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 27.0422, lng: 88.2635, address: 'Chauk Bazaar, Darjeeling, West Bengal 734101' },
    crowdStatus: 'high',
    crowdPercentage: 82,
    rating: 4.9,
    numReviews: 330,
    isPopular: true,
    entryFee: 'Steam Joyride ₹1,500; Diesel ₹1,000',
    timings: '08:00 AM - 05:00 PM',
    bestTimeToVisit: 'October to May',
    emergencyHelpline: '112 / DHR Control Room 0354-2252555',
    tags: ['Hill Station', 'Darjeeling', 'West Bengal', 'UNESCO', 'Heritage', 'Toy Train'],
  },
  {
    title: 'Happy Valley Historic Tea Estate',
    country: 'India',
    state: 'West Bengal',
    city: 'Darjeeling',
    category: 'Tourist Places',
    description: 'Established in 1854, Happy Valley is one of Darjeeling’s oldest and highest organic tea gardens, spanning 437 acres at 2,100 meters. Features guided tea plucking and factory aroma tastings.',
    shortDescription: '1854 organic heritage tea plantation offering tea factory aroma tours and plucking experiences.',
    images: [
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 27.0542, lng: 88.2618, address: 'Lebong Cart Road, Darjeeling, West Bengal 734101' },
    crowdStatus: 'low',
    crowdPercentage: 35,
    rating: 4.8,
    numReviews: 210,
    isPopular: true,
    entryFee: 'Guided Factory Tour ₹100',
    timings: '09:00 AM - 04:30 PM (Closed Sundays & Mondays)',
    bestTimeToVisit: 'March to November during tea harvesting seasons',
    emergencyHelpline: '112 / Happy Valley Estate Office',
    tags: ['Hill Station', 'Darjeeling', 'West Bengal', 'Tea Estate', 'Organic'],
  },
  {
    title: 'Peace Pagoda & Japanese Buddhist Temple',
    country: 'India',
    state: 'West Bengal',
    city: 'Darjeeling',
    category: 'Temples',
    description: 'Gleaming white Buddhist stupa constructed under the guidance of Nichidatsu Fuji, founder of the Nipponzan Myohoji Buddhist Order. Showcases four avatars of Lord Buddha and morning drum chanting.',
    shortDescription: 'Gleaming white Himalayan Buddhist stupa showcasing avatars of Buddha amidst pine forests.',
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 27.0298, lng: 88.2582, address: 'West Point, Jalapahar, Darjeeling, West Bengal 734102' },
    crowdStatus: 'low',
    crowdPercentage: 30,
    rating: 4.9,
    numReviews: 240,
    isPopular: true,
    entryFee: 'Free entry',
    timings: '04:30 AM - 07:00 PM (Meditation chanting at 04:30 AM & 04:30 PM)',
    bestTimeToVisit: 'All year round',
    emergencyHelpline: '112 / Japanese Temple Reception',
    tags: ['Hill Station', 'Darjeeling', 'West Bengal', 'Buddhist', 'Peace Pagoda', 'Temples'],
  },
  {
    title: 'Padmaja Naidu Himalayan Zoological Park & HMI',
    country: 'India',
    state: 'West Bengal',
    city: 'Darjeeling',
    category: 'Tourist Places',
    description: 'Renowned high-altitude zoological park dedicated to conserving endangered Himalayan wildlife including Red Pandas, Snow Leopards, and Himalayan Black Bears. Co-located with Himalayan Mountaineering Institute.',
    shortDescription: 'World-acclaimed high-altitude wildlife park home to endangered Red Pandas and Snow Leopards.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 27.0588, lng: 88.2548, address: 'Jawahar Parbat, Birch Hill, Darjeeling, West Bengal 734101' },
    crowdStatus: 'high',
    crowdPercentage: 76,
    rating: 4.8,
    numReviews: 310,
    isPopular: true,
    entryFee: '₹110 (Indians), ₹200 (Foreigners)',
    timings: '08:30 AM - 04:30 PM (Closed on Thursdays)',
    bestTimeToVisit: 'September to June',
    emergencyHelpline: '112 / Zoo Reception 0354-2253709',
    tags: ['Hill Station', 'Darjeeling', 'West Bengal', 'Red Panda', 'Wildlife Zoo', 'HMI'],
  },
  {
    title: 'Chowrasta Mall Road Promenade',
    country: 'India',
    state: 'West Bengal',
    city: 'Darjeeling',
    category: 'Shopping Areas',
    description: 'The historic pedestrian plaza in the heart of Darjeeling situated atop Observatory Hill ridge. Lined with colonial heritage benches, pony rides for kids, hot Darjeeling tea stalls, and vintage bookshops.',
    shortDescription: 'Pedestrian hill town plaza with open-air amphitheater, vintage benches, and Tibetan street food.',
    images: [
      'https://images.unsplash.com/photo-1597074866923-dc0589150458?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 27.0438, lng: 88.2684, address: 'The Mall, Chowrasta, Darjeeling, West Bengal 734101' },
    crowdStatus: 'high',
    crowdPercentage: 80,
    rating: 4.7,
    numReviews: 280,
    isPopular: true,
    entryFee: 'Free entry',
    timings: 'Open 24 hours (Shops 09:00 AM - 08:30 PM)',
    bestTimeToVisit: 'Throughout the year',
    emergencyHelpline: '112 / Chowrasta Police Kiosk',
    tags: ['Hill Station', 'Darjeeling', 'West Bengal', 'Chowrasta', 'Shopping Areas'],
  },
  {
    title: 'Rock Garden & Ganga Maya Water Park',
    country: 'India',
    state: 'West Bengal',
    city: 'Darjeeling',
    category: 'Tourist Places',
    description: 'A multi-tiered terraced garden carved directly out of rugged mountain rock around a natural roaring mountain waterfall in the Chunnu Summer Valley, 10 km down from Darjeeling town.',
    shortDescription: 'Terraced stone rock garden with cascading mountain waterfalls, bridges, and flowerbeds.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 27.0212, lng: 88.2288, address: 'Chunnu Summer Falls, Bloomfield, Darjeeling, West Bengal 734102' },
    crowdStatus: 'low',
    crowdPercentage: 35,
    rating: 4.6,
    numReviews: 170,
    isPopular: false,
    entryFee: '₹20 (Indians), ₹50 (Foreigners)',
    timings: '08:00 AM - 05:00 PM',
    bestTimeToVisit: 'March to June, September to December',
    emergencyHelpline: '112 / Bloomfield Forest Checkpoint',
    tags: ['Hill Station', 'Darjeeling', 'West Bengal', 'Rock Garden', 'Waterfall'],
  },

  // =========================================================================
  // 8. JAMMU & KASHMIR (SRINAGAR / GULMARG / PAHALGAM) (ENSURED HILL STATIONS)
  // =========================================================================
  {
    title: 'Gulmarg Gondola & Apharwat Peak Snowfields',
    country: 'India',
    state: 'Jammu & Kashmir',
    city: 'Gulmarg',
    category: 'Hill Stations',
    description: 'The world’s second highest operating cable car reaching an altitude of 3,980 meters at Apharwat Peak. World-class alpine ski destination offering powdery snow and Pir Panjal mountain panoramas.',
    shortDescription: 'World’s second-highest operating cable car reaching 3,980m Apharwat Peak ski snowfields.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 34.0544, lng: 74.3806, address: 'Gondola Base Station, Gulmarg, Jammu and Kashmir 193403' },
    crowdStatus: 'high',
    crowdPercentage: 84,
    rating: 4.9,
    numReviews: 390,
    isPopular: true,
    entryFee: 'Phase 1 ₹740; Phase 2 ₹950',
    timings: '09:00 AM - 05:00 PM',
    bestTimeToVisit: 'December to March for skiing; May to September for summer alpine blooms',
    emergencyHelpline: '112 / JKSDMA 1070 / Tourist Police Gulmarg 01954-254426',
    tags: ['Hill Station', 'Gulmarg', 'Jammu & Kashmir', 'Gondola', 'Snow', 'Skiing'],
  },
  {
    title: 'Pahalgam Betaab Valley & Sheshnag Stream',
    country: 'India',
    state: 'Jammu & Kashmir',
    city: 'Pahalgam',
    category: 'Hill Stations',
    description: 'Picture-postcard alpine valley named after the Bollywood movie Betaab, framed by deodar and pine forests, snow-clad mountain backdrops, and the rushing turquoise Lidder and Sheshnag rivers.',
    shortDescription: 'Idyllic alpine meadow with crystal streams, snow-draped mountains, and Bollywood film history.',
    images: [
      'https://images.unsplash.com/photo-1597074866923-dc0589150458?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 34.0289, lng: 75.3458, address: 'Betaab Valley, Pahalgam, Anantnag, Jammu and Kashmir 192126' },
    crowdStatus: 'moderate',
    crowdPercentage: 62,
    rating: 4.9,
    numReviews: 340,
    isPopular: true,
    entryFee: 'Park entry ₹100',
    timings: '08:00 AM - 06:00 PM',
    bestTimeToVisit: 'April to October, winter for snow trekking',
    emergencyHelpline: '112 / Pahalgam Police 01936-243222',
    tags: ['Hill Station', 'Pahalgam', 'Jammu & Kashmir', 'Betaab Valley', 'Lidder River'],
  },
  {
    title: 'Sonamarg Meadow of Gold & Thajiwas Glacier',
    country: 'India',
    state: 'Jammu & Kashmir',
    city: 'Sonamarg',
    category: 'Hill Stations',
    description: 'Situated at 2,730 meters on the bank of the Nallah Sindh, Sonamarg is the Meadow of Gold. Gateway to the Thajiwas Glacier with pony trails, pristine alpine flowers, and high snow mountains.',
    shortDescription: 'High-altitude Meadow of Gold offering pony treks to the glistening Thajiwas Glacier.',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 34.3052, lng: 75.2954, address: 'Thajiwas Track, Sonamarg, Ganderbal, Jammu and Kashmir 191203' },
    crowdStatus: 'moderate',
    crowdPercentage: 58,
    rating: 4.8,
    numReviews: 280,
    isPopular: true,
    entryFee: 'Free entry (Pony ride ₹800-₹1,500 optional)',
    timings: '07:00 AM - 06:00 PM',
    bestTimeToVisit: 'May to October',
    emergencyHelpline: '112 / Sonamarg Police 0194-2416225',
    tags: ['Hill Station', 'Sonamarg', 'Jammu & Kashmir', 'Glacier', 'Alpine'],
  },
  {
    title: 'Dal Lake Shikara Cruise & Floating Market',
    country: 'India',
    state: 'Jammu & Kashmir',
    city: 'Srinagar',
    category: 'Hill Stations',
    description: 'The Jewel in the Crown of Kashmir. A pristine 18 sq km lake famous for hand-carved cedar houseboats, floating vegetable and flower markets at dawn, and relaxing wooden Shikara rides.',
    shortDescription: 'Iconic Jewel of Kashmir featuring hand-carved houseboats and dawn floating bazaars.',
    images: [
      'https://images.unsplash.com/photo-1597074866923-dc0589150458?w=1200&auto=format&fit=crop&q=85',
    ],
    location: { lat: 34.0837, lng: 74.8389, address: 'Boulevard Road, Dal Lake, Srinagar, Jammu and Kashmir 190001' },
    crowdStatus: 'high',
    crowdPercentage: 79,
    rating: 4.9,
    numReviews: 420,
    isPopular: true,
    entryFee: 'Shikara ₹700 to ₹1,200 per hour',
    timings: 'Open 24 hours (Floating market 05:00 AM - 07:00 AM)',
    bestTimeToVisit: 'April to October, winter for icy chill',
    emergencyHelpline: '112 / Tourist Police Srinagar 0194-2452222',
    tags: ['Hill Station', 'Srinagar', 'Jammu & Kashmir', 'Dal Lake', 'Shikara', 'Houseboats'],
  },
];

/**
 * Ensure all hill station destinations exist in MongoDB.
 * Uses upsert by (title + city) so it's safe to run on every server startup.
 */
const ensureHillStationDestinations = async () => {
  try {
    const operations = hillStationDestinations.map((d, index) => {
      const generatedSlug = (
        d.title.toLowerCase().replace(/[^\w ]+/g, '').replace(/ +/g, '-') +
        '-' +
        d.city.toLowerCase().replace(/ +/g, '-') +
        '-' +
        (3000 + index)
      );

      return {
        updateOne: {
          filter: { title: d.title, city: d.city },
          update: {
            $set: {
              ...d,
            },
            $setOnInsert: {
              slug: generatedSlug,
            },
          },
          upsert: true,
        },
      };
    });

    const result = await Destination.bulkWrite(operations);
    const totalCount = await Destination.countDocuments({
      city: { $in: ['Shimla', 'Manali', 'Mussoorie', 'Nainital', 'Rishikesh', 'Ooty', 'Darjeeling', 'Gulmarg', 'Pahalgam', 'Sonamarg', 'Srinagar'] },
    });
    console.log(`[Hill Stations] Ensured hill station destinations in catalog: ${result.upsertedCount} inserted, ${result.modifiedCount} updated. Total active hill station spots: ${totalCount}`);
    return totalCount;
  } catch (error) {
    console.error('[Hill Stations] Error ensuring hill station destinations:', error);
    return 0;
  }
};

module.exports = {
  hillStationDestinations,
  ensureHillStationDestinations,
};
