const Zone = require('../models/Zone');

const NATIONAL_LANDSLIDE_SOURCE = {
  label: 'National Disaster Management Authority (NDMA) — Landslide Risk & Hazard Guidelines',
  url: 'https://ndma.gov.in/landslide',
};
const NATIONAL_FLOOD_SOURCE = {
  label: 'National Disaster Management Authority (NDMA) — River Rapid & Flash Flood Guidance',
  url: 'https://ndma.gov.in/floods-dos-donts',
};
const HPSDMA_SOURCE = {
  label: 'Himachal Pradesh State Disaster Management Authority (HPSDMA)',
  url: 'https://hpsdma.nic.in/',
};
const JKSDMA_SOURCE = {
  label: 'Jammu & Kashmir State Disaster Management Authority (JKSDMA)',
  url: 'https://jksdma.jk.gov.in/',
};
const USDMA_SOURCE = {
  label: 'Uttarakhand State Disaster Management Authority (USDMA)',
  url: 'https://usdma.uk.gov.in/',
};

const DESTINATIONS = [
  {
    key: 'shimla',
    label: 'Shimla, Himachal Pradesh',
    sources: [HPSDMA_SOURCE, NATIONAL_LANDSLIDE_SOURCE, NATIONAL_FLOOD_SOURCE],
    emergencyContacts: [
      { label: 'National Emergency', number: '112', service: 'Police / Fire / Rescue' },
      { label: 'HPSDMA State Disaster Control Room', number: '1070', service: '24x7 State Emergency Operation' },
      { label: 'DDMA District Emergency Shimla', number: '1077', service: 'District Disaster Control' },
      { label: 'Shimla Police Control Room', number: '0177-2803211', service: 'Mall Road Police HQ' },
      { label: 'Ambulance Triage', number: '108', service: 'Emergency Medical Services' },
      { label: 'Tourist Assistance Helpline', number: '1363', service: 'Ministry of Tourism' },
    ],
    locations: [
      {
        name: 'The Ridge, Shimla',
        latitude: 31.1048,
        longitude: 77.1734,
        riskLevel: 'Low',
        hazardType: 'Pedestrian Heritage Promenade / Low Risk',
        description: 'Iconic open-air cultural and public promenade overlooking the Dhauladhar ranges. Strictly vehicle-free with pedestrian paving and tourist assistance kiosks.',
        safeZone: {
          radius: 350,
          label: 'Recommended Public Safe Zone',
          description: 'Fully paved pedestrian concourse with CCTV surveillance and quick emergency vehicle access.',
        },
        cautionZone: {
          radius: 500,
          label: 'Slope Fringe Caution Area',
          description: 'Steep steps descending towards Lakkar Bazaar; beware of black ice during winter mornings.',
        },
        hazardZone: {
          radius: 0,
          label: 'No Active Hazard',
          description: 'High-stability zone on the ridge spine. Maintain standard pedestrian caution.',
        },
        safetyInstructions: 'Stay on the paved concourse. Follow municipal staff guidelines during snowfall or icy mornings. Do not lean over historic valley railings.',
        nearbySafePoints: [
          'Shimla Police Control Room (Mall Rd - 150m)',
          'Indira Gandhi Medical College (IGMC) Hospital (1.2 km)',
          'Lakkar Bazaar Tourist Assistance Booth (200m)',
        ],
        emergencyInformation: [
          { label: 'Shimla Police Control Room', number: '0177-2803211' },
          { label: 'DDMA Shimla', number: '1077' },
          { label: 'National Emergency', number: '112' },
          { label: 'Ambulance', number: '108' },
        ],
        category: 'geofence',
      },
      {
        name: 'Mall Road & Scandal Point',
        latitude: 31.1044,
        longitude: 77.1718,
        riskLevel: 'Low',
        hazardType: 'Regulated Pedestrian Corridor',
        description: 'Prime colonial heritage shopping street, bustling with tourists and local artisans. Completely barred to motor vehicles except authorized emergency ambulances.',
        safeZone: {
          radius: 400,
          label: 'Recommended Pedestrian Safe Buffer',
          description: 'Wide, well-lit pedestrian walkway with emergency first-aid posts.',
        },
        cautionZone: {
          radius: 600,
          label: 'Lower Bazaar Staircase Caution',
          description: 'Steep stepped alleyways leading to Lower Bazaar; can become slippery during monsoon rain.',
        },
        hazardZone: {
          radius: 0,
          label: 'No Active Hazard',
          description: 'Protected municipal precinct. Keep personal belongings safe during peak evening footfall.',
        },
        safetyInstructions: 'Keep emergency lanes clear for official response carts. Wear textured rubber footwear in sub-zero frost conditions.',
        nearbySafePoints: [
          'Sadar Police Station (Mall Rd - 100m)',
          'The Ridge Information Center (180m)',
          'IGMC Medical Trauma Ward (1.4 km)',
        ],
        emergencyInformation: [
          { label: 'Sadar Police Station', number: '0177-2812344' },
          { label: 'Tourist Police Helpline', number: '1363' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'geofence',
      },
      {
        name: 'IGMC Hospital Emergency Zone',
        latitude: 31.1047,
        longitude: 77.1926,
        riskLevel: 'Low',
        hazardType: 'Apex Himalayan Trauma & Medical Safe Point',
        description: 'Himachal Pradesh premier tertiary teaching hospital and round-the-clock emergency medical response center for high-altitude illness and trauma.',
        safeZone: {
          radius: 400,
          label: 'Critical Medical Safe Haven',
          description: 'Emergency trauma center, oxygen cylinders, ICU, blood bank, and 24x7 doctor coverage.',
        },
        cautionZone: {
          radius: 550,
          label: 'Ambulance Transit Perimeter',
          description: 'Give immediate right of way to incoming siren-sounding ambulances on circular road.',
        },
        hazardZone: {
          radius: 0,
          label: 'No Active Hazard',
          description: 'Designated disaster casualty collection point for Shimla district.',
        },
        safetyInstructions: 'Immediate casualty intake for hypothermia, acute mountain sickness, fracture injuries, or respiratory distress.',
        nearbySafePoints: [
          'IGMC Trauma Triage Wing',
          'Sanjauli Police Outpost (800m)',
          'The Ridge Concourse (1.2 km)',
        ],
        emergencyInformation: [
          { label: 'IGMC Emergency Hotline', number: '0177-2804251' },
          { label: 'State Ambulance Triage', number: '108' },
          { label: 'HPSDMA State Control', number: '1070' },
        ],
        category: 'medical',
      },
      {
        name: 'Sanjauli Junction & Bypass Chokepoint',
        latitude: 31.1034,
        longitude: 77.1969,
        riskLevel: 'Moderate',
        hazardType: 'Steep Hillside Traffic Congestion & Pedestrian Chokepoint',
        description: 'Crucial vehicular intersection connecting Shimla with Dhalli, Kufri, and Upper Shimla. High vehicle volume on tight hillside curves with blind turns.',
        safeZone: {
          radius: 200,
          label: 'Marked Overhead Walkway & Sidewalk',
          description: 'Pedestrian footbridge and protected sidewalk.',
        },
        cautionZone: {
          radius: 380,
          label: 'Active Traffic Chokepoint',
          description: 'Heavy vehicular convergence; avoid standing on roadway edges or blind road bends.',
        },
        hazardZone: {
          radius: 460,
          label: 'Steep Valley Side Drop-off',
          description: 'Precautionary drop-off buffer along lower unshielded slope curves.',
        },
        safetyInstructions: 'Always use designated pedestrian overhead crossing. Avoid walking along the road during morning dense fog or freezing drizzle.',
        nearbySafePoints: [
          'Sanjauli Police Post (200m)',
          'IGMC Hospital Emergency (800m)',
          'Sanjauli Civil Hospital (350m)',
        ],
        emergencyInformation: [
          { label: 'Traffic Police Helpline', number: '0177-2651850' },
          { label: 'DDMA Shimla', number: '1077' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Kufri High-Altitude Snow Slopes',
        latitude: 31.0975,
        longitude: 77.2670,
        riskLevel: 'Moderate',
        hazardType: 'Severe Seasonal Blizzard, Snow Slips & Frostbite Exposure',
        description: 'High elevation destination (8,600 ft) renowned for Himalayan panoramic views, ski slopes, and nature parks. Subject to sudden drops in temperature and heavy snowfall.',
        safeZone: {
          radius: 250,
          label: 'Main Resort Concourse & Heated Pavilions',
          description: 'HPTDC Amber Cafe, verified ticketing kiosks, and patrolled main parking lot.',
        },
        cautionZone: {
          radius: 450,
          label: 'Unpaved Mule & Snow Trail Corridor',
          description: 'Steep snowy trails with mixed pedestrian and horse movement.',
        },
        hazardZone: {
          radius: 650,
          label: 'Unpatrolled Wild Valley Slopes',
          description: 'Steep unmaintained wilderness slopes prone to snow drifts and zero-visibility blizzards.',
        },
        safetyInstructions: 'Dress in thermal multi-layers with waterproof outer shell. Do not venture onto unmarked slopes. Return to main parking before 5:00 PM sunset.',
        nearbySafePoints: [
          'Kufri Police Post (300m)',
          'HPTDC Amber Restaurant Shelter',
          'Theog Sub-Divisional Hospital (11 km)',
        ],
        emergencyInformation: [
          { label: 'Kufri Police Station', number: '0177-2648232' },
          { label: 'Mountain Search & Rescue (HPSDMA)', number: '1070' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Summer Hill Station & Forest Ravine',
        latitude: 31.1059,
        longitude: 77.1370,
        riskLevel: 'High',
        hazardType: 'Active Monsoon Landslide Prone Slope & Subsidence Zone',
        description: 'Geologically sensitive Himalayan slope below HP University and Kalka-Shimla heritage railway. Documented history of severe monsoon landslides and sinking terrain.',
        safeZone: {
          radius: 120,
          label: 'Summer Hill Station Platform Shelter',
          description: 'Station masonry building and reinforced platform area.',
        },
        cautionZone: {
          radius: 260,
          label: 'Slope Precaution Buffer',
          description: 'Hillside road with potential small rockfalls during downpours.',
        },
        hazardZone: {
          radius: 450,
          label: 'Active Landslide & Slope Runout Corridor',
          description: 'High-risk steep gorge vulnerable to debris flow and slope failure after heavy rainfall.',
        },
        safetyInstructions: 'DANGER: Stay off steep unpaved trails during and within 48 hours of intense rain. If cracking sounds, tumbling pebbles, or sudden muddy water are observed, move immediately uphill to high ground.',
        nearbySafePoints: [
          'HP University Campus Central Gate (550m)',
          'Boileauganj Police Station (1.1 km)',
          'IGMC Hospital Emergency (3.5 km)',
        ],
        emergencyInformation: [
          { label: 'Shimla Landslide Rapid Action (DDMA)', number: '1077' },
          { label: 'HPSDMA State Emergency HQ', number: '1070' },
          { label: 'SDRF Himachal Pradesh', number: '0177-2629939' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Dhalli Hillside Road & Tunnel Bypass',
        latitude: 31.1150,
        longitude: 77.2025,
        riskLevel: 'Moderate',
        hazardType: 'Falling Rocks, Loose Scree & Monsoon Water Inundation',
        description: 'Vital mountain highway artery hugging steep rock cliffs towards Mashobra and Rampur. Prone to shooting stones during heavy precipitation.',
        safeZone: {
          radius: 180,
          label: 'Dhalli Market & Civil Station',
          description: 'Open market area with concrete structures and police chowki.',
        },
        cautionZone: {
          radius: 380,
          label: 'Single-Lane Tunnel Approach',
          description: 'Maintain careful vehicle spacing; watch for merging mountain traffic.',
        },
        hazardZone: {
          radius: 480,
          label: 'Loose Scree Mountain Face',
          description: 'Rockfall hazard along exposed mountain cutting.',
        },
        safetyInstructions: 'Maintain at least 40 meters distance from preceding vehicles. Never stop underneath unstable, unnetted rock faces. Obey roadside digital hazard signs.',
        nearbySafePoints: [
          'Dhalli Police Station (250m)',
          'Sanjauli Bypass Overpass (1.2 km)',
          'IGMC Medical Center (2.8 km)',
        ],
        emergencyInformation: [
          { label: 'Dhalli Police Station', number: '0177-2841221' },
          { label: 'National Highway Patrol', number: '1073' },
          { label: 'DDMA Shimla', number: '1077' },
        ],
        category: 'hazard',
      },
      {
        name: 'Annandale Meadow & Army Heritage Base',
        latitude: 31.0933,
        longitude: 77.1591,
        riskLevel: 'Low',
        hazardType: 'Wide Open Valley Plateau / Army Helipad Evacuation Hub',
        description: 'Vast scenic plateau nestled in deodar forests, hosting the Army Heritage Museum and golf course. Acts as designated disaster relief helipad for Shimla.',
        safeZone: {
          radius: 380,
          label: 'Evacuation Green Zone & Heritage Concourse',
          description: 'Level ground with emergency helipad and military medical first-aid.',
        },
        cautionZone: {
          radius: 500,
          label: 'Access Road Forest Incline',
          description: 'Winding forest incline; check vehicle brakes before descent.',
        },
        hazardZone: {
          radius: 0,
          label: 'No Active Hazard',
          description: 'Extremely secure and stable terrain.',
        },
        safetyInstructions: 'Respect military security boundaries. Keep entry permits and valid photo ID accessible for verification at the main gate.',
        nearbySafePoints: [
          'Army Heritage Center Safe Post (150m)',
          'Kaithu Police Post (1.1 km)',
          'IGMC Emergency Center (2.9 km)',
        ],
        emergencyInformation: [
          { label: 'Army Base Emergency Unit', number: '0177-2652610' },
          { label: 'National Emergency', number: '112' },
          { label: 'DDMA Shimla', number: '1077' },
        ],
        category: 'attraction',
      },
    ],
  },
  {
    key: 'jammu-kashmir',
    label: 'Jammu & Kashmir',
    sources: [JKSDMA_SOURCE, NATIONAL_LANDSLIDE_SOURCE, NATIONAL_FLOOD_SOURCE],
    emergencyContacts: [
      { label: 'National Emergency', number: '112', service: 'Integrated Police / Ambulance / Rescue' },
      { label: 'JKSDMA State Emergency Operation Centre', number: '1070', service: '24x7 Disaster Management EOC' },
      { label: 'District Emergency Srinagar', number: '1077', service: 'District Magistrate Control Room' },
      { label: 'JK Police Control Room Srinagar', number: '0194-2455222', service: 'Police Central Command' },
      { label: 'SDRF Headquarters Srinagar', number: '0194-2455333', service: 'State Disaster Response Force' },
      { label: 'Jammu & Kashmir Tourist Police', number: '1363', service: 'Tourist Protection Cell' },
    ],
    locations: [
      {
        name: 'Tourist Reception Centre (TRC) Srinagar',
        latitude: 34.0690,
        longitude: 74.8377,
        riskLevel: 'Low',
        hazardType: 'Central Tourist Assistance & Transit Safety Hub',
        description: 'Primary administrative hub for J&K Tourism, housing verified travel desks, registered taxi unions, and emergency safety cells.',
        safeZone: {
          radius: 400,
          label: 'Recommended Tourism Safe Zone',
          description: 'Government complex with dedicated tourist police station and round-the-clock advisory counters.',
        },
        cautionZone: {
          radius: 550,
          label: 'Residency Road Traffic Convergence',
          description: 'Busy transit junction; use designated pedestrian crossings.',
        },
        hazardZone: {
          radius: 0,
          label: 'No Active Hazard',
          description: 'Protected administrative perimeter.',
        },
        safetyInstructions: 'Obtain verified route status for Gulmarg, Sonamarg, and Pahalgam here. Register your travel details with the Tourist Police Desk.',
        nearbySafePoints: [
          'TRC Tourist Police Station (50m)',
          'SMHS Hospital (2.2 km)',
          'Sher-i-Kashmir Indoor Stadium Safe Refuge (600m)',
        ],
        emergencyInformation: [
          { label: 'TRC Tourist Police', number: '0194-2502279' },
          { label: 'JK Police Control Room', number: '0194-2455222' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'geofence',
      },
      {
        name: 'Dal Lake Boulevard & Ghat Promenade',
        latitude: 34.0850,
        longitude: 74.8810,
        riskLevel: 'Moderate',
        hazardType: 'Deep Water Edge, Sudden Shore Swells & Overcrowding',
        description: 'World-famous waterfront promenade skirting Dal Lake. Dense gathering of tourists, shikara docks, and houseboats.',
        safeZone: {
          radius: 280,
          label: 'Boulevard Pedestrian Walkway',
          description: 'Paved, illuminated promenade equipped with edge railings and lifeguard buoys.',
        },
        cautionZone: {
          radius: 420,
          label: 'Shikara Boarding Jetties',
          description: 'Floating wooden docks; step carefully and keep children by the hand.',
        },
        hazardZone: {
          radius: 520,
          label: 'Deep Water Navigation Channels',
          description: 'Hazardous deep cold-water channels. Swimming is strictly prohibited.',
        },
        safetyInstructions: 'Wearing certified life jackets is mandatory on all Shikara and motorboat rides. Never step onto unlit or damaged wooden jetties after sunset.',
        nearbySafePoints: [
          'Nehru Park River Police Post (200m)',
          'TRC Srinagar Hub (2.8 km)',
          'Khyber Medical Hospital (3.2 km)',
        ],
        emergencyInformation: [
          { label: 'River Police Dal Lake', number: '0194-2452222' },
          { label: 'SDRF Boat Rescue Unit', number: '0194-2455333' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'SKIMS Soura Apex Hospital Zone',
        latitude: 34.1353,
        longitude: 74.8004,
        riskLevel: 'Low',
        hazardType: 'Premier Himalayan Medical & Trauma Safe Haven',
        description: 'Sher-i-Kashmir Institute of Medical Sciences (SKIMS) is J&K largest tertiary referral hospital and premier trauma center.',
        safeZone: {
          radius: 500,
          label: 'Medical Emergency Zone',
          description: '24x7 trauma resuscitation, blood bank, hyperbaric unit, and high-altitude pulmonary edema (HAPE) treatment.',
        },
        cautionZone: {
          radius: 650,
          label: 'Hospital Approach Corridor',
          description: 'Maintain open lane for emergency ambulances.',
        },
        hazardZone: {
          radius: 0,
          label: 'No Active Hazard',
          description: 'Designated highest-tier medical refuge.',
        },
        safetyInstructions: 'For urgent medical rescue, high-altitude pulmonary distress, or fractures, report directly to the SKIMS Emergency Triage Building.',
        nearbySafePoints: [
          'SKIMS Emergency Trauma Block',
          'Soura Police Station (350m)',
          'Hazratbal Tourist Assistance Booth (1.8 km)',
        ],
        emergencyInformation: [
          { label: 'SKIMS Emergency Control', number: '0194-2401013' },
          { label: 'State Ambulance Triage', number: '108' },
          { label: 'JKSDMA Disaster Command', number: '1070' },
        ],
        category: 'medical',
      },
      {
        name: 'Gulmarg Gondola Base & Apharwat Trailhead',
        latitude: 34.0510,
        longitude: 74.3805,
        riskLevel: 'Moderate',
        hazardType: 'High-Altitude Blizzard, Sub-Zero Hypothermia & Dense Fog',
        description: 'World highest operational cable car terminal ascending to Apharwat Peak (13,780 ft). Weather can invert from clear skies to zero-visibility blizzard in under 30 minutes.',
        safeZone: {
          radius: 300,
          label: 'Gondola Terminal & Heated Shelters',
          description: 'Heated indoor waiting halls, medical oxygen dispensary, and ski patrol HQ.',
        },
        cautionZone: {
          radius: 500,
          label: 'Lower Ski Slopes & Beginner Bowls',
          description: 'Marked ski routes; watch for passing snowboarders and ski school groups.',
        },
        hazardZone: {
          radius: 750,
          label: 'Apharwat Backcountry Avalanche Chutes',
          description: 'Dangerous unpatrolled alpine slopes susceptible to snow avalanches.',
        },
        safetyInstructions: 'Check Snow & Avalanche Study Establishment (SASE) avalanche bulletins before ascent. High altitude can trigger AMS; descend immediately if breathing difficulty occurs.',
        nearbySafePoints: [
          'High Altitude Warfare School (HAWS) Post (400m)',
          'Gulmarg Police Station (650m)',
          'Tangmarg Sub-District Hospital (12 km)',
        ],
        emergencyInformation: [
          { label: 'Gulmarg Ski Patrol & Rescue', number: '01954-254424' },
          { label: 'Baramulla Disaster Management', number: '1077' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Pahalgam Central Valley & Taxi Stand',
        latitude: 34.0161,
        longitude: 75.3149,
        riskLevel: 'Low',
        hazardType: 'Protected Valley Floor Tourism Hub',
        description: 'Serene valley town (7,200 ft) at the junction of the Lidder and Sheshnag streams. Staging base for the Amarnath Yatra and alpine meadow treks.',
        safeZone: {
          radius: 400,
          label: 'Recommended Town Safe Center',
          description: 'Verified police booths, tourist reception desk, and administrative safe zone.',
        },
        cautionZone: {
          radius: 520,
          label: 'Lidder River Bank Access',
          description: 'Steep river banks; keep away from river edge during seasonal snowmelt.',
        },
        hazardZone: {
          radius: 0,
          label: 'No Active Hazard',
          description: 'Well-monitored tourist town center.',
        },
        safetyInstructions: 'Hire registered mountain guides and verified pony handlers displaying official union badges only. Check daily trail passes at the tourism center.',
        nearbySafePoints: [
          'Pahalgam Tourist Police Post (150m)',
          'Sub-District Hospital Pahalgam (400m)',
          'Pahalgam Club Safe Assembly Area (300m)',
        ],
        emergencyInformation: [
          { label: 'Pahalgam Tourist Police', number: '01936-243206' },
          { label: 'Anantnag Disaster Control', number: '1077' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'geofence',
      },
      {
        name: 'Betaab Valley & Lidder Riverfront Flash Flood Corridor',
        latitude: 34.0030,
        longitude: 75.3540,
        riskLevel: 'Moderate',
        hazardType: 'Fast Glacial River Currents & Sudden Water Level Surges',
        description: 'Picturesque valley flanked by snow-capped peaks and the roaring Lidder River. Glacial snowmelt and upper cloudbursts can cause rapid, violent river surges.',
        safeZone: {
          radius: 250,
          label: 'Valley Upper Lawn & Visitor Gazebos',
          description: 'High-ground landscaped gardens, bridges, and covered restaurant pavilions.',
        },
        cautionZone: {
          radius: 400,
          label: 'Pebbled Riverbank Approaches',
          description: 'Water edge zones; step back immediately if sirens sound or water turns muddy.',
        },
        hazardZone: {
          radius: 550,
          label: 'Active Riverbed Flash Flood Zone',
          description: 'Submerged boulders and rapid undertow; crossing or bathing is strictly prohibited.',
        },
        safetyInstructions: 'Never pitch tents or lounge on mid-stream boulder islands. Heed upstream flood sirens from Kolahoi glacier watershed.',
        nearbySafePoints: [
          'Betaab Valley Main Security Gate (250m)',
          'Pahalgam Town Center (7 km)',
          'Lidder Camp Assistance Kiosk (1.2 km)',
        ],
        emergencyInformation: [
          { label: 'Anantnag Flood Control Room', number: '01932-222870' },
          { label: 'SDRF Quick Response Team', number: '1070' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Sonamarg Meadow & Thajiwas Glacier Footpath',
        latitude: 34.3037,
        longitude: 75.2937,
        riskLevel: 'Moderate',
        hazardType: 'Glacier Crevasses, Cold Streams & Unpredictable Mountain Weather',
        description: 'Golden Meadow (8,960 ft) gateway to Ladakh along the Sindh River. Famous for the Thajiwas Glacier where snow persists year-round.',
        safeZone: {
          radius: 300,
          label: 'Main Market & Visitor Parking Concourse',
          description: 'Market amenities, tourist information kiosk, and telecom connectivity zone.',
        },
        cautionZone: {
          radius: 480,
          label: 'Glacier Valley Track',
          description: 'Rocky scree and moraine path; wear ankle-supported hiking boots.',
        },
        hazardZone: {
          radius: 650,
          label: 'Active Thajiwas Glacier Moraine Edge',
          description: 'Slippery black ice, unstable snow bridges, and hidden glacial streams.',
        },
        safetyInstructions: 'Do not venture onto unsupported snow bridges in afternoon heat. Hire experienced registered mountain guides for glacier hikes. Carry warm waterproofs.',
        nearbySafePoints: [
          'Sonamarg Police Station (350m)',
          'Sonamarg Primary Health Centre (400m)',
          'BRO Project Beacon Camp (1.5 km)',
        ],
        emergencyInformation: [
          { label: 'Sonamarg Police Post', number: '0194-2416225' },
          { label: 'Ganderbal Disaster Management', number: '1077' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Zoji La Pass High-Altitude Cliff & Avalanche Corridor',
        latitude: 34.2800,
        longitude: 75.4870,
        riskLevel: 'High',
        hazardType: 'Critical Avalanche Chutes, Sheer Unshielded Drops & Sub-Zero Blizzards',
        description: 'Strategic high-altitude mountain pass (11,575 ft) connecting Kashmir with Ladakh. Known as one of the world most treacherous vehicular passes with sheer vertical drops and frequent snow slides.',
        safeZone: {
          radius: 100,
          label: 'Captain Mor Overlook Reinforced Shelter',
          description: 'Concrete bunker shelter and army transit checkpoint.',
        },
        cautionZone: {
          radius: 250,
          label: 'Convoy Staging Road Corridor',
          description: 'Strict one-way traffic convoy rules managed by traffic police.',
        },
        hazardZone: {
          radius: 600,
          label: 'Critical Avalanche & Sheer Precipice Zone',
          description: 'Narrow unpaved ledge with multi-thousand-foot vertical drops and active rock/snow slides.',
        },
        safetyInstructions: 'DANGER: Strictly follow BRO/Traffic convoy timings. Vehicles must carry snow chains and emergency rations. Overtaking is strictly prohibited. Never halt beneath marked avalanche chutes.',
        nearbySafePoints: [
          'BRO Project Beacon Emergency Shelter (1.5 km)',
          'Sonamarg Base Staging Camp (15 km)',
          'Minamarg Military Checkpoint (12 km)',
        ],
        emergencyInformation: [
          { label: 'Zojila Traffic Police Control', number: '01954-254424' },
          { label: 'Kargil Disaster Control Room', number: '1077' },
          { label: 'Army Mountain Emergency Helpline', number: '1070' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
    ],
  },
  {
    key: 'mussoorie',
    label: 'Mussoorie, Uttarakhand',
    sources: [USDMA_SOURCE, NATIONAL_LANDSLIDE_SOURCE, NATIONAL_FLOOD_SOURCE],
    emergencyContacts: [
      { label: 'National Emergency', number: '112', service: 'Integrated Police / Ambulance / Fire' },
      { label: 'USDMA State Emergency Operation Centre', number: '1070', service: 'State Disaster Management Authority' },
      { label: 'DDMA Dehradun Disaster Control', number: '1077', service: 'District Emergency Center' },
      { label: 'Mussoorie Police Kotwali', number: '0135-2632003', service: 'Mussoorie Police HQ' },
      { label: 'Uttarakhand SDRF HQ', number: '9456596190', service: 'State Disaster Response Force' },
      { label: 'Uttarakhand Tourism Helpline', number: '1363', service: 'Tourist Safety Helpline' },
    ],
    locations: [
      {
        name: 'Library Chowk (Gandhi Chowk West)',
        latitude: 30.4599,
        longitude: 78.0644,
        riskLevel: 'Low',
        hazardType: 'Primary Pedestrian Town Gateway & Safe Hub',
        description: 'Vibrant western anchor of Mussoorie Mall Road, home to the historic 1843 Library building, taxi stands, and major tourist amenities.',
        safeZone: {
          radius: 350,
          label: 'Town Center Safe Zone',
          description: 'Paved, fully illuminated pedestrian concourse with police presence and taxi regulation booths.',
        },
        cautionZone: {
          radius: 480,
          label: 'Cart Road Vehicular Approach',
          description: 'Tight hillside switchbacks with shuttle taxis and buses.',
        },
        hazardZone: {
          radius: 0,
          label: 'No Active Hazard',
          description: 'Stable urban crest of the ridge.',
        },
        safetyInstructions: 'Follow pedestrian lane markings. For local excursions to Kempty or Cloud End, hire verified pre-paid union taxis only.',
        nearbySafePoints: [
          'Mussoorie Police Kotwali (150m)',
          'Civil Hospital Mussoorie (650m)',
          'GMVN Tourism Information Centre (100m)',
        ],
        emergencyInformation: [
          { label: 'Mussoorie Police Kotwali', number: '0135-2632003' },
          { label: 'DDMA Dehradun', number: '1077' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'geofence',
      },
      {
        name: 'Picture Palace & Kulri Bazaar Hub',
        latitude: 30.4550,
        longitude: 78.0772,
        riskLevel: 'Low',
        hazardType: 'Commercial Pedestrian Visitor Promenade',
        description: 'Eastern terminus of Mall Road featuring historic cinemas, bakeries, and direct connectivity to Landour cantonment.',
        safeZone: {
          radius: 350,
          label: 'Pedestrian Commercial Safe Zone',
          description: 'Well-surveilled shopping area with police patrol and first-aid facilities.',
        },
        cautionZone: {
          radius: 500,
          label: 'Incline Road to Landour',
          description: 'Steep road with single-lane pinch points.',
        },
        hazardZone: {
          radius: 0,
          label: 'No Active Hazard',
          description: 'Secured municipal sector.',
        },
        safetyInstructions: 'Avoid parking on steep roadway grades. In heavy winter frost, use pedestrian footpaths treated with anti-skid sand.',
        nearbySafePoints: [
          'Kulri Police Outpost (80m)',
          'Landour Community Hospital (1.5 km)',
          'Library Chowk (1.8 km)',
        ],
        emergencyInformation: [
          { label: 'Kulri Police Outpost', number: '0135-2632223' },
          { label: 'State Ambulance Triage', number: '108' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'geofence',
      },
      {
        name: 'Landour Bazaar & Sisters Bazaar Ridge',
        latitude: 30.4618,
        longitude: 78.0805,
        riskLevel: 'Moderate',
        hazardType: 'Steep Narrow Switchbacks, Blind Corners & Cliff Edges',
        description: 'Charming historic British cantonment ridge (7,500 ft) renowned for dense pine forests and Himalayan views. Characterized by single-lane cliffside roads.',
        safeZone: {
          radius: 200,
          label: 'Sisters Bazaar & Char Dukan Heritage Safe Courtyard',
          description: 'Stable heritage cluster with cafes, post office, and cantonment office.',
        },
        cautionZone: {
          radius: 350,
          label: 'Single-Lane Cantonment Road',
          description: 'Blind bends; vehicles must honk before turns and yield to uphill traffic.',
        },
        hazardZone: {
          radius: 460,
          label: 'Unshielded Forest Drop-offs',
          description: 'Steep hillside drops lacking crash barriers; do not lean or step past safety fences.',
        },
        safetyInstructions: 'Drive only in low gear. Pedestrians must step onto designated stone passing niches when vehicles approach. No parking on narrow curves.',
        nearbySafePoints: [
          'Landour Community Hospital (LCH - 300m)',
          'Landour Cantonment Police Post (400m)',
          'Char Dukan Rest Zone (600m)',
        ],
        emergencyInformation: [
          { label: 'Landour Community Hospital', number: '0135-2632053' },
          { label: 'Landour Cantonment Board', number: '0135-2632345' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Company Garden & Municipal Botanical Park',
        latitude: 30.4755,
        longitude: 78.0315,
        riskLevel: 'Low',
        hazardType: 'Enclosed Landscaped Botanical Grounds',
        description: 'Popular family tourist attraction featuring flower carpets, amusement rides, and an artificial waterfall set in a gentle valley bowl.',
        safeZone: {
          radius: 320,
          label: 'Park Recreational Safe Haven',
          description: 'Enclosed garden with paved paths, picnic shelters, and on-site staff.',
        },
        cautionZone: {
          radius: 450,
          label: 'Waverly Road Hillside Access',
          description: 'Narrow hillside access lane.',
        },
        hazardZone: {
          radius: 0,
          label: 'No Active Hazard',
          description: 'Family-friendly low-risk environment.',
        },
        safetyInstructions: 'Remain on maintained botanical walking tracks. Children must wear buoyancy vests on pedal boat rides.',
        nearbySafePoints: [
          'Park Security Outpost (at gate)',
          'Waverly Police Post (1.2 km)',
          'Civil Hospital Mussoorie (3.2 km)',
        ],
        emergencyInformation: [
          { label: 'Uttarakhand Tourism Helpline', number: '1363' },
          { label: 'Mussoorie Police Kotwali', number: '0135-2632003' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'attraction',
      },
      {
        name: 'Kempty Falls Gorge & Plunge Pool',
        latitude: 30.4921,
        longitude: 78.0127,
        riskLevel: 'Moderate',
        hazardType: 'Slippery Algae Steps, Sudden Flash Spate & Heavy Water Volume',
        description: 'Perennial tiered waterfall plunging 40 feet into a natural rock basin. Monsoon rains upstream can trigger instantaneous 10-fold water surges.',
        safeZone: {
          radius: 200,
          label: 'Upper Terrace & Ropeway Station Safe Zone',
          description: 'High masonry terraces, cable car terminal, and market shelters above flood line.',
        },
        cautionZone: {
          radius: 380,
          label: 'Stepped Gorge Descent',
          description: 'Steep, wet concrete steps with metal railings; watch your footing.',
        },
        hazardZone: {
          radius: 480,
          label: 'Waterfall Plunge Pool & Downstream Flash Channel',
          description: 'Active flash-flood hazard zone. High risk during and after rainfall.',
        },
        safetyInstructions: 'Mandatory evacuation of lower plunge pool if water turns muddy brown or if whistles blow. Never jump into unmeasured natural pools. Comply with ropeway operators.',
        nearbySafePoints: [
          'Kempty Police Station (300m)',
          'Upper Market Tourist Refuge (150m)',
          'Mussoorie Civil Hospital (14 km)',
        ],
        emergencyInformation: [
          { label: 'Kempty Police Station', number: '0135-2630040' },
          { label: 'Tehri Garhwal Disaster Management', number: '1077' },
          { label: 'Uttarakhand SDRF', number: '9456596190' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Bhatta Falls & Ropeway Canyon',
        latitude: 30.4386,
        longitude: 78.0809,
        riskLevel: 'Moderate',
        hazardType: 'Steep Rocky Incline, Mossy Boulders & Swift Stream Flow',
        description: 'Natural waterfall and stream located 7 km before Mussoorie on the Dehradun highway. Features ropeway access and natural swimming ponds.',
        safeZone: {
          radius: 220,
          label: 'Upper Ropeway Terminal & Restaurant Deck',
          description: 'Sturdy concrete promenade with visitor amenities.',
        },
        cautionZone: {
          radius: 350,
          label: 'Natural Pool Embankment',
          description: 'Rocky terrain with uneven surfaces.',
        },
        hazardZone: {
          radius: 480,
          label: 'Downstream Forest Ravine',
          description: 'Fast seasonal runoff and submerged rocks.',
        },
        safetyInstructions: 'Avoid wading during high monsoon discharge. Wear rubber-tread footwear. Do not explore unmapped canyon channels downriver.',
        nearbySafePoints: [
          'Bhatta Ropeway Command Office (100m)',
          'Dehradun-Mussoorie Highway Police Checkpost (1.5 km)',
          'Mussoorie Civil Hospital (5 km)',
        ],
        emergencyInformation: [
          { label: 'Dehradun Highway Patrol', number: '1073' },
          { label: 'DDMA Dehradun', number: '1077' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Jharipani Falls Trailhead & Monsoon Ravine',
        latitude: 30.4254,
        longitude: 78.0794,
        riskLevel: 'High',
        hazardType: 'Active Landslide Vulnerability, Mudslides & Loose Scree Slopes',
        description: 'Wild forest waterfall accessed via an unpaved 1.5 km trek from Jharipani. The surrounding hillside is designated as highly susceptible to monsoon landslides.',
        safeZone: {
          radius: 100,
          label: 'Oak Grove School Road Junction',
          description: 'Paved main road with vehicular access.',
        },
        cautionZone: {
          radius: 250,
          label: 'Unpaved Trek Corridor',
          description: 'Slippery dirt path prone to washed-out sections.',
        },
        hazardZone: {
          radius: 460,
          label: 'Active Landslide Scar & Blind Gorge',
          description: 'Severe geological hazard zone during rain; risk of tumbling boulders and mudflows.',
        },
        safetyInstructions: 'DANGER: Strictly prohibited during IMD orange or red rainfall alerts. If soil erosion, fresh cracks, or trickling pebbles are seen on the slopes, retreat immediately. Trek only in daylight.',
        nearbySafePoints: [
          'Oak Grove School Security Gate (600m)',
          'Jharipani Police Post (1.2 km)',
          'Mussoorie Hospital (6.8 km)',
        ],
        emergencyInformation: [
          { label: 'DDMA Dehradun Landslide Hotline', number: '1077' },
          { label: 'Uttarakhand SDRF Rescue', number: '9456596190' },
          { label: 'USDMA State Control', number: '1070' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Hathipaon & Cloud End Wilderness Track',
        latitude: 30.4814,
        longitude: 78.0350,
        riskLevel: 'Moderate',
        hazardType: 'Dense Fog Shrouds, Wild Animal Corridors & Exposed Valley Edges',
        description: 'Western extremity of Mussoorie where thick oak and deodar forests mark the edge of the Benog Wildlife Sanctuary. Offers expansive views of the Aglar river valley.',
        safeZone: {
          radius: 250,
          label: 'Sir George Everest Heritage Pavilion',
          description: 'Fenced observatory grounds with historical museum and open meadow.',
        },
        cautionZone: {
          radius: 420,
          label: 'Forested Walking Tracks',
          description: 'Unpaved sanctuary paths; stay with your group.',
        },
        hazardZone: {
          radius: 550,
          label: 'Aglar Valley Vertical Drop-offs',
          description: 'Unprotected cliff edges dropping several hundred feet into valley.',
        },
        safetyInstructions: 'Stay strictly on marked heritage trails. Do not walk along the edge of unbarricaded cliffs for photography. Return to the main road before twilight.',
        nearbySafePoints: [
          'George Everest House Information Post (200m)',
          'Mussoorie Forest Guard Chowki (800m)',
          'Library Chowk (4.5 km)',
        ],
        emergencyInformation: [
          { label: 'Mussoorie Forest Control Room', number: '0135-2632335' },
          { label: 'Mussoorie Police Kotwali', number: '0135-2632003' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
    ],
  },
  {
    key: 'rishikesh',
    label: 'Rishikesh, Uttarakhand',
    sources: [USDMA_SOURCE, NATIONAL_FLOOD_SOURCE, NATIONAL_LANDSLIDE_SOURCE],
    emergencyContacts: [
      { label: 'National Emergency', number: '112', service: 'Integrated Police / River Rescue / Ambulance' },
      { label: 'USDMA State Emergency Operation Centre', number: '1070', service: 'Disaster Management Authority' },
      { label: 'DDMA Dehradun Disaster Control', number: '1077', service: 'District Emergency Center' },
      { label: 'Kotwali Police Station Rishikesh', number: '0135-2430012', service: 'City Police Command' },
      { label: 'Uttarakhand SDRF River Rescue Command', number: '9456596190', service: 'Water Rescue / Rapid Response' },
      { label: 'AIIMS Rishikesh Trauma Hotline', number: '0135-2462999', service: 'Level-1 Apex Trauma' },
    ],
    locations: [
      {
        name: 'AIIMS Rishikesh Apex Trauma Center',
        latitude: 30.0730,
        longitude: 78.2850,
        riskLevel: 'Low',
        hazardType: 'Apex Level-1 Trauma Hospital & Disaster Medical Hub',
        description: 'Premier national institute with 24x7 Level-1 trauma, neurosurgery, hyperbaric oxygen chambers, and dedicated disaster casualty wards.',
        safeZone: {
          radius: 500,
          label: 'Primary Healthcare Safe Haven',
          description: 'Dedicated emergency triage, helipad, and continuous specialist physician presence.',
        },
        cautionZone: {
          radius: 650,
          label: 'Veerbhadra Road Access Corridor',
          description: 'Keep clear for incoming high-speed ambulances.',
        },
        hazardZone: {
          radius: 0,
          label: 'No Active Hazard',
          description: 'Designated highest-level emergency safety refuge for Garhwal.',
        },
        safetyInstructions: 'Direct emergency intake for drowning resuscitations, rafting spinal injuries, acute trauma, or snakebites.',
        nearbySafePoints: [
          'AIIMS Emergency Trauma Building',
          'Veerbhadra Police Outpost (600m)',
          'Rishikesh Railway Junction (3.5 km)',
        ],
        emergencyInformation: [
          { label: 'AIIMS Trauma Emergency', number: '0135-2462999' },
          { label: 'State Ambulance Dispatch', number: '108' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'medical',
      },
      {
        name: 'Parmarth Niketan & Swarg Ashram Concourse',
        latitude: 30.1260,
        longitude: 78.3170,
        riskLevel: 'Low',
        hazardType: 'Regulated Cultural Riverfront & Ashram Precinct',
        description: 'World-renowned spiritual ashram on the eastern banks of the holy Ganga, famous for its daily sunset Ganga Aarti ceremony.',
        safeZone: {
          radius: 350,
          label: 'Recommended Cultural Safe Zone',
          description: 'Wide stone ghat with permanent seating tiers, safety chains, and SDRF water rescue posts.',
        },
        cautionZone: {
          radius: 480,
          label: 'River Shoreline Buffer',
          description: 'Fast-moving water along the lowest steps; step cautiously.',
        },
        hazardZone: {
          radius: 0,
          label: 'No Active Hazard',
          description: 'Extensively patrolled and illuminated public spiritual area.',
        },
        safetyInstructions: 'Sit on marked stone tiers during evening Aarti. Do not enter water past designated safety railings. Obey SDRF boat lifeguards.',
        nearbySafePoints: [
          'Parmarth Niketan Security Desk (50m)',
          'Swarg Ashram Police Post (250m)',
          'AIIMS Rishikesh (6 km)',
        ],
        emergencyInformation: [
          { label: 'Swarg Ashram Police Post', number: '0135-2440268' },
          { label: 'SDRF River Rescue Squad', number: '9456596190' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'geofence',
      },
      {
        name: 'Triveni Ghat & Sacred Confluence Steps',
        latitude: 30.1038,
        longitude: 78.2942,
        riskLevel: 'Moderate',
        hazardType: 'High-Velocity River Currents, Sudden Dam Discharges & High Density',
        description: 'Central holy bathing ghat where Ganga, Yamuna, and Saraswati are spiritually confluence. Very swift river velocity and rapid water level fluctuations from upstream dam releases.',
        safeZone: {
          radius: 220,
          label: 'Upper Promenade & Pavilion Safe Area',
          description: 'Paved, elevated promenade with changing rooms and security chowki.',
        },
        cautionZone: {
          radius: 380,
          label: 'Bathing Steps with Safety Chains',
          description: 'Always grip iron safety chains while taking holy dips.',
        },
        hazardZone: {
          radius: 480,
          label: 'Deep Underwater Mainstream & Undertow',
          description: 'Severe undertow currents past the chains; swimming into deep stream is forbidden.',
        },
        safetyInstructions: 'Always hold installed iron safety chains. Upstream dams (Tehri / Chilla) may release water; if warning sirens sound, exit water immediately. Supervise children at all times.',
        nearbySafePoints: [
          'Triveni Ghat Police Chowki (80m)',
          'Mayakund Community Shelter (300m)',
          'Nirmal Ashram Hospital (1.5 km)',
        ],
        emergencyInformation: [
          { label: 'Triveni Ghat Police Chowki', number: '0135-2430012' },
          { label: 'SDRF Water Rescue Command', number: '9456596190' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Ram Jhula Suspension Bridge & Western Square',
        latitude: 30.1264,
        longitude: 78.3199,
        riskLevel: 'Moderate',
        hazardType: 'High Pedestrian & Two-Wheeler Density, Suspension Sway & River Embankments',
        description: 'Iconic 450-foot iron suspension bridge spanning the Ganga between Muni Ki Reti and Swarg Ashram. High foot traffic and occasional pedestrian congestion.',
        safeZone: {
          radius: 250,
          label: 'Muni Ki Reti Public Square Safe Zone',
          description: 'Spacious landing with tourist information, taxi stands, and police station.',
        },
        cautionZone: {
          radius: 380,
          label: 'Suspension Bridge Span & Walkway',
          description: 'Moving bridge span; do not block pedestrian flow or lean over railings.',
        },
        hazardZone: {
          radius: 460,
          label: 'Unshielded Riverbank Drop-offs',
          description: 'Steep rock slopes directly below bridge pylons.',
        },
        safetyInstructions: 'Do not stop on the suspension span for photos during crowded intervals. Follow one-way foot traffic instructions. Keep mobile phones and belongings secured.',
        nearbySafePoints: [
          'Muni Ki Reti Police Station (200m)',
          'Ganga Kinare Safe Assembly Point (400m)',
          'AIIMS Rishikesh Trauma Center (5.5 km)',
        ],
        emergencyInformation: [
          { label: 'Muni Ki Reti Police Station', number: '0135-2430263' },
          { label: 'DDMA Tehri Garhwal', number: '1077' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Lakshman Jhula & Tapovan Riverfront Walkway',
        latitude: 30.1300,
        longitude: 78.3240,
        riskLevel: 'Moderate',
        hazardType: 'Heritage Bridge Preservation Status & High River Surge',
        description: 'Historic landmark bridge and vibrant Tapovan cafe corridor. The heritage pedestrian bridge undergoes structural conservation with new crossing alternatives.',
        safeZone: {
          radius: 220,
          label: 'Tapovan High Terrace & Cafe Promenade',
          description: 'Elevated bedrock terrace with medical clinics and cafes well above flood mark.',
        },
        cautionZone: {
          radius: 380,
          label: 'Heritage Bridge Approach Paths',
          description: 'Narrow walking alleys leading to boat ferry points.',
        },
        hazardZone: {
          radius: 480,
          label: 'Rocky River Vortex Zone',
          description: 'Swirling water eddies around river boulders; no bathing.',
        },
        safetyInstructions: 'Use only registered ferry boats or the newly opened Bajrang Setu crossing. Never clamber across slippery riverside boulders.',
        nearbySafePoints: [
          'Tapovan Police Post (200m)',
          'Lakshman Jhula Police Chowki (150m)',
          'Government Civil Hospital Rishikesh (4 km)',
        ],
        emergencyInformation: [
          { label: 'Lakshman Jhula Police Chowki', number: '0135-2430012' },
          { label: 'Uttarakhand SDRF', number: '9456596190' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Shivpuri White Water Rafting Launch & Flash Flood Canyon',
        latitude: 30.1280,
        longitude: 78.3360,
        riskLevel: 'High',
        hazardType: 'Class III-IV Rapids (Roller Coaster, Golf Course) & Flash Spates',
        description: 'Epicenter of Himalayan river rafting on the Ganga (16 km upstream from Rishikesh). Powerful Class III & IV rapids surrounded by steep canyon walls.',
        safeZone: {
          radius: 150,
          label: 'Licensed Campsite Terrace & Briefing Zone',
          description: 'High alluvial river terrace above the 100-year flood line with certified equipment depot.',
        },
        cautionZone: {
          radius: 300,
          label: 'Beach Gear-Up & Staging Sand',
          description: 'Mandatory lifejacket fitting and safety paddle drills.',
        },
        hazardZone: {
          radius: 550,
          label: 'Turbulent White Water Canyon',
          description: 'High-energy rapids with violent hydraulics, whirlpools, and sudden river volume spikes.',
        },
        safetyInstructions: 'DANGER: Embark only with Uttarakhand Tourism certified licensed outfitters accompanied by a safety rescue kayaker. Compulsory Level-5 PFD and helmet fastened at all times. Rafting is strictly banned after 4:30 PM and during monsoon.',
        nearbySafePoints: [
          'Shivpuri Police Outpost (250m)',
          'Camp Red Chilli High Bluff Shelter (350m)',
          'AIIMS Rishikesh Level-1 Trauma (12 km)',
        ],
        emergencyInformation: [
          { label: 'SDRF White Water Rescue Unit', number: '9456596190' },
          { label: 'Shivpuri Police Outpost', number: '01378-227525' },
          { label: 'USDMA State Control Room', number: '1070' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Neelkanth Mahadev Hillside Road & Landslide Runout',
        latitude: 30.0880,
        longitude: 78.3220,
        riskLevel: 'High',
        hazardType: 'Severe Monsoon Landslides, Boulder Fall & Steep Mountain Gorge Drops',
        description: 'Steep winding mountain pilgrimage highway ascending through dense Manikoot forest to the sacred Neelkanth shrine (4,360 ft). Extremely prone to rockfalls and slope collapse during rains.',
        safeZone: {
          radius: 120,
          label: 'Neelkanth Temple Outer Bazaar Platform',
          description: 'Reinforced concrete square and temple security office.',
        },
        cautionZone: {
          radius: 300,
          label: 'Upper Temple Approach',
          description: 'Slow-moving pilgrimage traffic.',
        },
        hazardZone: {
          radius: 550,
          label: 'Active Mountain Cutting & Shooting Stone Zone',
          description: 'High-risk steep cliff road vulnerable to boulders tumbling from overhead heights.',
        },
        safetyInstructions: 'DANGER: Strictly avoid travel during moderate or heavy rainfall and IMD weather warnings. If small pebbles or dust trickles down the rock face, stop vehicles in covered shelter bays immediately.',
        nearbySafePoints: [
          'Neelkanth Police Station (200m)',
          'Garuda Chatti Police Post (5 km)',
          'AIIMS Trauma Center Rishikesh (9 km)',
        ],
        emergencyInformation: [
          { label: 'Pauri Garhwal Disaster Emergency', number: '1077' },
          { label: 'Uttarakhand SDRF HQ', number: '9456596190' },
          { label: 'USDMA State Emergency', number: '1070' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
      {
        name: 'Marine Drive Kaudiyala Overlook & Undertow Shore',
        latitude: 30.1190,
        longitude: 78.3850,
        riskLevel: 'Moderate',
        hazardType: 'Steep River Embankment, Swift Undertow & Deep River Trenches',
        description: 'Scenic riverfront drive along NH-58 towards Kaudiyala, featuring sandy river beaches and expansive views of the jade-green Ganga.',
        safeZone: {
          radius: 250,
          label: 'Highway Overlook & Rest Plaza',
          description: 'Reinforced metal barrier viewpoints with parking bays.',
        },
        cautionZone: {
          radius: 420,
          label: 'Sandy Beach Descent Path',
          description: 'Loose sand and gravel incline.',
        },
        hazardZone: {
          radius: 500,
          label: 'Deep Undercurrent Mainstream (The Wall Rapid)',
          description: 'Submerged vertical rock cliffs creating treacherous reverse undertow.',
        },
        safetyInstructions: 'Strictly observe "No Swimming" warning placards. The tranquil surface masks extreme subsurface current velocity. Stay behind barrier chains.',
        nearbySafePoints: [
          'Byasi Police Checkpost (1.2 km)',
          'Kaudiyala GMVN Tourist Rest House (1.8 km)',
          'Shivpuri Police Outpost (8 km)',
        ],
        emergencyInformation: [
          { label: 'National Highway Patrol', number: '1073' },
          { label: 'Uttarakhand SDRF Rapid Unit', number: '9456596190' },
          { label: 'National Emergency', number: '112' },
        ],
        category: 'hazard',
      },
    ],
  },
  // ── MANALI, Himachal Pradesh ─────────────────────────────
  {
    key: 'manali',
    label: 'Manali, Himachal Pradesh',
    sources: [HPSDMA_SOURCE, NATIONAL_LANDSLIDE_SOURCE, NATIONAL_FLOOD_SOURCE],
    emergencyContacts: [
      { label: 'National Emergency', number: '112', service: 'Police / Fire / Rescue' },
      { label: 'HPSDMA State Disaster Control Room', number: '1070', service: '24x7 State Emergency Operation' },
      { label: 'DDMA District Emergency Kullu', number: '1077', service: 'District Disaster Control' },
      { label: 'Manali Police Station', number: '01902-252340', service: 'Manali Local Police' },
      { label: 'Ambulance Triage', number: '108', service: 'Emergency Medical Services' },
      { label: 'Tourist Assistance Helpline', number: '1363', service: 'Ministry of Tourism' },
    ],
    locations: [
      {
        name: 'Hadimba Temple & Cedar Forest',
        latitude: 32.2434,
        longitude: 77.1892,
        riskLevel: 'Low',
        hazardType: 'Heritage Site / Low Risk',
        description: 'Ancient Hadimba Devi temple set within dense deodar cedar forest. Well-maintained pathways and tourist infrastructure.',
        safeZone: { radius: 350, label: 'Recommended Heritage Safe Zone', description: 'Paved paths with guardrails and tourist assistance kiosks.' },
        cautionZone: { radius: 500, label: 'Forest Trail Caution', description: 'Narrow forest trails can be slippery after rain. Watch for uneven ground.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Protected heritage site with regular maintenance.' },
        safetyInstructions: 'Stay on marked paths. Do not feed wild langur monkeys. Wear proper footwear on forest trails.',
        nearbySafePoints: ['Manali Police Station (1.5 km)', 'Lady Willingdon Hospital (2 km)', 'Tourist Information Center (1.2 km)'],
        emergencyInformation: [{ label: 'Manali Police', number: '01902-252340' }, { label: 'National Emergency', number: '112' }],
        category: 'geofence',
      },
      {
        name: 'Mall Road, Manali',
        latitude: 32.2396,
        longitude: 77.1887,
        riskLevel: 'Low',
        hazardType: 'Commercial Pedestrian Zone',
        description: 'Main shopping and dining boulevard of Manali, lined with hotels, cafes, and handicraft shops. Well-lit with police presence.',
        safeZone: { radius: 400, label: 'Safe Commercial Zone', description: 'Well-patrolled pedestrian area with emergency vehicle access.' },
        cautionZone: { radius: 550, label: 'Traffic Caution', description: 'Narrow side lanes with mixed vehicle and pedestrian traffic.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Established commercial district with municipal surveillance.' },
        safetyInstructions: 'Keep valuables secure. Watch for traffic in connecting lanes. Emergency services accessible via Mall Road.',
        nearbySafePoints: ['Manali Bus Stand (300m)', 'SDM Office Manali (500m)', 'Manali Civil Hospital (1 km)'],
        emergencyInformation: [{ label: 'Manali Police', number: '01902-252340' }, { label: 'Ambulance', number: '108' }],
        category: 'geofence',
      },
      {
        name: 'Solang Valley',
        latitude: 32.3153,
        longitude: 77.1573,
        riskLevel: 'Moderate',
        hazardType: 'Avalanche-Prone Adventure Zone',
        description: 'Popular ski and adventure sports valley at 2,560m. Prone to sudden weather changes, avalanche corridors in winter, and icy roads.',
        safeZone: { radius: 300, label: 'Base Camp Safe Area', description: 'Valley floor with ropeway station and organized activity zones.' },
        cautionZone: { radius: 600, label: 'Slope Caution Zone', description: 'Steep slopes with avalanche risk during heavy snowfall. Stay on marked routes.' },
        hazardZone: { radius: 800, label: 'Avalanche Corridor', description: 'Upper slopes susceptible to avalanches. Restricted during heavy snowfall.' },
        safetyInstructions: 'Always adventure with certified guides. Check weather advisories. Carry warm clothing and emergency supplies. Avoid upper slopes during snowstorms.',
        nearbySafePoints: ['Solang Valley Ropeway Station (500m)', 'HPTDC Resort (2 km)', 'Manali Civil Hospital (14 km)'],
        emergencyInformation: [{ label: 'HPSDMA', number: '1070' }, { label: 'National Emergency', number: '112' }],
        category: 'caution',
      },
      {
        name: 'Rohtang Pass Road',
        latitude: 32.3722,
        longitude: 77.2475,
        riskLevel: 'High',
        hazardType: 'High-Altitude Landslide & Avalanche Zone',
        description: 'Mountain pass at 3,978m connecting Kullu Valley to Lahaul-Spiti. Extremely steep switchbacks, frequent landslides, and zero-visibility fog.',
        safeZone: { radius: 200, label: 'Controlled Checkpoint', description: 'Atal Tunnel approach with organized traffic management.' },
        cautionZone: { radius: 600, label: 'Winding Road Caution', description: 'Sharp hairpin bends with unprotected cliff edges. Slow traffic required.' },
        hazardZone: { radius: 900, label: 'Active Landslide Zone', description: 'Multiple landslide-prone segments. Road closures common during monsoon and heavy snowfall.' },
        safetyInstructions: 'Never drive in fog or ice without chains. Carry oxygen cylinder above 3,500m. Follow BRO advisory. Road closes Oct–May.',
        nearbySafePoints: ['Atal Tunnel North Portal (6 km)', 'Marhi HPTDC Rest House (4 km)', 'BRO Emergency Post (2 km)'],
        emergencyInformation: [{ label: 'BRO Emergency', number: '01902-252012' }, { label: 'HPSDMA', number: '1070' }, { label: 'National Emergency', number: '112' }],
        category: 'hazard',
      },
      {
        name: 'Old Manali Village',
        latitude: 32.2512,
        longitude: 77.1881,
        riskLevel: 'Low',
        hazardType: 'Heritage Village / Low Risk',
        description: 'Charming traditional Kullu-style village with wooden temples, guesthouses, and riverside cafes along Manalsu stream.',
        safeZone: { radius: 350, label: 'Village Safe Zone', description: 'Walkable village core with established guesthouses and restaurants.' },
        cautionZone: { radius: 500, label: 'Stream Bank Caution', description: 'Manalsu Nala stream banks can flood during heavy monsoon rains.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Peaceful residential area with tourist-friendly infrastructure.' },
        safetyInstructions: 'Stay away from stream banks during rain. Carry a torch at night as some lanes are unlit. Respect local customs.',
        nearbySafePoints: ['Old Manali Temple (200m)', 'Manali Police Station (1.5 km)', 'Lady Willingdon Hospital (2.5 km)'],
        emergencyInformation: [{ label: 'Manali Police', number: '01902-252340' }, { label: 'Ambulance', number: '108' }],
        category: 'geofence',
      },
      {
        name: 'Beas River Rafting Point, Pirdi',
        latitude: 32.1725,
        longitude: 77.1256,
        riskLevel: 'Moderate',
        hazardType: 'River Rapids / Water Sports Zone',
        description: 'White-water rafting starting point on the Beas River with Grade II-III rapids. Controlled adventure activity zone.',
        safeZone: { radius: 250, label: 'Embarkation Safe Area', description: 'Organized launching ghats with safety equipment stations.' },
        cautionZone: { radius: 500, label: 'River Bank Caution', description: 'Slippery boulders and strong undercurrents near rapids.' },
        hazardZone: { radius: 700, label: 'Rapid Zone', description: 'Grade III rapids with powerful currents. Only with certified operators.' },
        safetyInstructions: 'Always wear life jackets. Raft only with licensed operators. Avoid swimming in rapids. Check water level advisories.',
        nearbySafePoints: ['Pirdi Police Outpost (500m)', 'Kullu District Hospital (15 km)', 'HPTDC Rafting Base (200m)'],
        emergencyInformation: [{ label: 'SDRF Kullu', number: '01902-222471' }, { label: 'National Emergency', number: '112' }],
        category: 'caution',
      },
      {
        name: 'Jogini Waterfall Trail',
        latitude: 32.2592,
        longitude: 77.1923,
        riskLevel: 'Moderate',
        hazardType: 'Steep Trekking Trail / Rockfall Zone',
        description: 'Popular 3 km trek to Jogini Falls through narrow forest trails and rocky terrain. Prone to rockfalls during and after rain.',
        safeZone: { radius: 200, label: 'Trailhead Safe Zone', description: 'Village starting point with shops and basic medical aid.' },
        cautionZone: { radius: 450, label: 'Steep Trail Caution', description: 'Loose scree and narrow paths. Risk of slipping on wet rocks.' },
        hazardZone: { radius: 650, label: 'Rockfall Zone Near Falls', description: 'Active rockfall area near the waterfall. Landslide debris during monsoon.' },
        safetyInstructions: 'Wear trekking shoes with grip. Avoid trek during or after heavy rain. Do not venture off marked trail. Carry water and first-aid kit.',
        nearbySafePoints: ['Vashisht Village (1 km)', 'Manali Civil Hospital (3 km)', 'Old Manali Police Post (2 km)'],
        emergencyInformation: [{ label: 'HPSDMA', number: '1070' }, { label: 'National Emergency', number: '112' }],
        category: 'caution',
      },
      {
        name: 'Vashisht Hot Springs',
        latitude: 32.2578,
        longitude: 77.1982,
        riskLevel: 'Low',
        hazardType: 'Geothermal Heritage Site / Low Risk',
        description: 'Ancient hot sulfur springs and temple complex with natural mineral water baths. Popular wellness and heritage site.',
        safeZone: { radius: 300, label: 'Temple Complex Safe Zone', description: 'Well-maintained bathing area with attendants and changing rooms.' },
        cautionZone: { radius: 450, label: 'Hot Water Caution', description: 'Water temperature varies. Test before bathing. Slippery wet stone floors.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Managed temple complex with regular maintenance.' },
        safetyInstructions: 'Test water temperature before entering. Do not leave children unattended. Slippery surfaces around springs.',
        nearbySafePoints: ['Vashisht Temple Trust Office (50m)', 'Manali Police Station (2 km)', 'Lady Willingdon Hospital (3 km)'],
        emergencyInformation: [{ label: 'Manali Police', number: '01902-252340' }, { label: 'Ambulance', number: '108' }],
        category: 'geofence',
      },
    ],
  },
  // ── NAINITAL, Uttarakhand ─────────────────────────────
  {
    key: 'nainital',
    label: 'Nainital, Uttarakhand',
    sources: [USDMA_SOURCE, NATIONAL_LANDSLIDE_SOURCE, NATIONAL_FLOOD_SOURCE],
    emergencyContacts: [
      { label: 'National Emergency', number: '112', service: 'Police / Fire / Rescue' },
      { label: 'USDMA State Disaster Control Room', number: '1070', service: '24x7 State Emergency Operation' },
      { label: 'DDMA District Emergency Nainital', number: '1077', service: 'District Disaster Control' },
      { label: 'Nainital Police Control Room', number: '05942-235400', service: 'Nainital Police HQ' },
      { label: 'Ambulance Triage', number: '108', service: 'Emergency Medical Services' },
      { label: 'Tourist Assistance Helpline', number: '1363', service: 'Ministry of Tourism' },
    ],
    locations: [
      {
        name: 'Naini Lake & Mall Road',
        latitude: 29.3919,
        longitude: 79.4542,
        riskLevel: 'Low',
        hazardType: 'Lake Promenade / Low Risk',
        description: 'Iconic crescent-shaped freshwater lake surrounded by the Mall Road commercial strip. Well-maintained tourist promenade with boating facilities.',
        safeZone: { radius: 400, label: 'Lakeside Safe Zone', description: 'Paved walkway around the lake with guardrails, police presence, and medical aid kiosks.' },
        cautionZone: { radius: 550, label: 'Boat Jetty Caution', description: 'Crowded during peak season. Watch for slippery jetty surfaces.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Well-regulated municipal lakefront area.' },
        safetyInstructions: 'Use authorized boating services only. Wear life jackets on boats. Keep children supervised near water.',
        nearbySafePoints: ['Nainital Police Station (300m)', 'B.D. Pandey Government Hospital (1 km)', 'Tourist Information Center (200m)'],
        emergencyInformation: [{ label: 'Nainital Police', number: '05942-235400' }, { label: 'National Emergency', number: '112' }],
        category: 'geofence',
      },
      {
        name: 'Naina Devi Temple',
        latitude: 29.3917,
        longitude: 79.4554,
        riskLevel: 'Low',
        hazardType: 'Heritage Temple / Low Risk',
        description: 'Sacred temple dedicated to Naina Devi at the north end of Naini Lake. Important Shakti Peeth pilgrimage site.',
        safeZone: { radius: 300, label: 'Temple Precinct Safe Zone', description: 'Well-organized temple complex with crowd management and security.' },
        cautionZone: { radius: 450, label: 'Stairway Caution', description: 'Steep temple steps can be crowded and slippery during festivals.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Protected heritage site with regular maintenance.' },
        safetyInstructions: 'Follow queue discipline during peak hours. Remove shoes before entering. Watch your step on wet staircases.',
        nearbySafePoints: ['Tallital Police Post (400m)', 'Naini Lake Boat House (200m)', 'B.D. Pandey Hospital (800m)'],
        emergencyInformation: [{ label: 'Nainital Police', number: '05942-235400' }, { label: 'Ambulance', number: '108' }],
        category: 'geofence',
      },
      {
        name: 'Snow View Point & Ropeway',
        latitude: 29.3990,
        longitude: 79.4523,
        riskLevel: 'Moderate',
        hazardType: 'High-Altitude Viewpoint / Slope Risk',
        description: 'Popular viewpoint at 2,270m offering panoramic Himalayan views. Accessible by aerial ropeway or steep trek.',
        safeZone: { radius: 250, label: 'Ropeway Station Safe Zone', description: 'Organized cable car boarding area with safety inspections.' },
        cautionZone: { radius: 500, label: 'Steep Path Caution', description: 'Narrow hiking trail with loose gravel. Icy conditions in winter.' },
        hazardZone: { radius: 700, label: 'Slope Instability Zone', description: 'Steep hillside prone to minor landslips during monsoon.' },
        safetyInstructions: 'Use ropeway during adverse weather instead of trekking. Avoid edges at viewpoint. Carry warm clothing in winter.',
        nearbySafePoints: ['Ropeway Lower Station (50m)', 'Nainital Mall Road (1.5 km)', 'Fire Station (2 km)'],
        emergencyInformation: [{ label: 'USDMA', number: '1070' }, { label: 'National Emergency', number: '112' }],
        category: 'caution',
      },
      {
        name: 'Naina Peak (China Peak)',
        latitude: 29.4086,
        longitude: 79.4628,
        riskLevel: 'Moderate',
        hazardType: 'High-Altitude Trek / Weather Risk',
        description: 'Highest point in Nainital at 2,615m. 6 km trek through dense oak and deodar forests with panoramic Himalayan views.',
        safeZone: { radius: 200, label: 'Summit Viewpoint', description: 'Flat observation area at the peak.' },
        cautionZone: { radius: 500, label: 'Forest Trail Caution', description: 'Dense forest with poor mobile signal. Trail markers can be unclear.' },
        hazardZone: { radius: 700, label: 'Weather Exposure Zone', description: 'Sudden fog and thunderstorms common. Risk of hypothermia in winter.' },
        safetyInstructions: 'Start early morning. Carry water, snacks, and warm layers. Inform hotel before trekking. Do not trek alone or after dark.',
        nearbySafePoints: ['Forest Rest House (2 km)', 'Nainital Mall Road (6 km)', 'B.D. Pandey Hospital (7 km)'],
        emergencyInformation: [{ label: 'USDMA', number: '1070' }, { label: 'National Emergency', number: '112' }],
        category: 'caution',
      },
      {
        name: 'Landslide Zone – Balia Nala',
        latitude: 29.3868,
        longitude: 79.4491,
        riskLevel: 'High',
        hazardType: 'Active Landslide Zone / Subsidence',
        description: 'Historically unstable slope along Balia Nala ravine. Major landslide events recorded in 1880 and recent years. Ground subsidence ongoing.',
        safeZone: { radius: 150, label: 'Reinforced Road Segment', description: 'Retaining wall-supported section of road with drainage.' },
        cautionZone: { radius: 400, label: 'Subsidence Caution Zone', description: 'Ground cracking and sinking observed. Buildings under monitoring.' },
        hazardZone: { radius: 700, label: 'Active Landslide Zone', description: 'Documented landslide corridor. Avoid during and after heavy rain.' },
        safetyInstructions: 'Do not stop vehicles in this zone. Avoid walking near slope edges. Immediately leave area if you hear cracking sounds or see debris movement.',
        nearbySafePoints: ['Tallital Bus Stand (1 km)', 'Nainital Fire Station (1.5 km)', 'B.D. Pandey Hospital (2 km)'],
        emergencyInformation: [{ label: 'DDMA Nainital', number: '1077' }, { label: 'USDMA', number: '1070' }, { label: 'National Emergency', number: '112' }],
        category: 'hazard',
      },
      {
        name: 'Eco Cave Gardens',
        latitude: 29.3855,
        longitude: 79.4633,
        riskLevel: 'Low',
        hazardType: 'Tourist Attraction / Low Risk',
        description: 'Network of natural rock caves and hanging gardens near Sukhatal. Family-friendly attraction with guided tours.',
        safeZone: { radius: 300, label: 'Garden Complex Safe Zone', description: 'Managed tourist attraction with guides and safety equipment.' },
        cautionZone: { radius: 450, label: 'Cave Interior Caution', description: 'Narrow cave passages. Watch head clearance and slippery rocks.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Maintained attraction with regular safety inspections.' },
        safetyInstructions: 'Follow guide instructions inside caves. Carry a flashlight. Not suitable for claustrophobic visitors. Watch for bats.',
        nearbySafePoints: ['Sukhatal Area Police Post (500m)', 'Nainital Mall Road (2 km)', 'B.D. Pandey Hospital (2.5 km)'],
        emergencyInformation: [{ label: 'Nainital Police', number: '05942-235400' }, { label: 'Ambulance', number: '108' }],
        category: 'geofence',
      },
      {
        name: 'Tiffin Top (Dorothy\'s Seat)',
        latitude: 29.3804,
        longitude: 79.4530,
        riskLevel: 'Moderate',
        hazardType: 'Hilltop Trek / Slope Risk',
        description: 'Scenic hilltop at 2,292m with 360° views. Accessible via 4 km trek or horseback ride through Ayarpatta forest.',
        safeZone: { radius: 200, label: 'Summit Platform', description: 'Flat viewpoint area with seating and safety rails.' },
        cautionZone: { radius: 450, label: 'Forest Trail Caution', description: 'Steep horse trail with loose stones. Muddy after rain.' },
        hazardZone: { radius: 650, label: 'Cliff Edge Zone', description: 'Unfenced cliff edges on approach routes. Dangerous in fog.' },
        safetyInstructions: 'Stay on marked trails. Do not approach cliff edges. Trek before noon to avoid afternoon fog. Carry water.',
        nearbySafePoints: ['Ayarpatta Forest Gate (2 km)', 'Nainital Mall Road (4 km)', 'Fire Station (4.5 km)'],
        emergencyInformation: [{ label: 'Nainital Police', number: '05942-235400' }, { label: 'National Emergency', number: '112' }],
        category: 'caution',
      },
    ],
  },
  // ── OOTY (Udhagamandalam), Tamil Nadu ─────────────────────────────
  {
    key: 'ooty',
    label: 'Ooty, Tamil Nadu',
    sources: [
      { label: 'Tamil Nadu State Disaster Management Authority (TNSDMA)', url: 'https://tnsdma.tn.gov.in/' },
      NATIONAL_LANDSLIDE_SOURCE,
      NATIONAL_FLOOD_SOURCE,
    ],
    emergencyContacts: [
      { label: 'National Emergency', number: '112', service: 'Police / Fire / Rescue' },
      { label: 'TNSDMA State Disaster Control Room', number: '1070', service: '24x7 State Emergency Operation' },
      { label: 'DDMA Nilgiris', number: '1077', service: 'District Disaster Control' },
      { label: 'Ooty Police Station', number: '0423-2443001', service: 'Ooty Town Police' },
      { label: 'Ambulance Triage', number: '108', service: 'Emergency Medical Services' },
      { label: 'Tourist Assistance Helpline', number: '1363', service: 'Ministry of Tourism' },
    ],
    locations: [
      {
        name: 'Ooty Lake & Boat House',
        latitude: 11.4064,
        longitude: 76.6932,
        riskLevel: 'Low',
        hazardType: 'Lake Recreation / Low Risk',
        description: 'Scenic artificial lake built in 1824 with boating facilities, gardens, and a mini train ride. Major family tourist attraction.',
        safeZone: { radius: 400, label: 'Lakeside Recreation Zone', description: 'Well-maintained boating area with life-saving equipment and trained staff.' },
        cautionZone: { radius: 550, label: 'Lake Edge Caution', description: 'Marshy lake edges can be slippery. Keep children supervised.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Managed municipal recreation area.' },
        safetyInstructions: 'Use authorized boats only. Wear life jackets. Do not swim in the lake. Keep children away from lake edges.',
        nearbySafePoints: ['Ooty Police Station (1 km)', 'Government Hospital Ooty (1.5 km)', 'Tourist Information Center (800m)'],
        emergencyInformation: [{ label: 'Ooty Police', number: '0423-2443001' }, { label: 'National Emergency', number: '112' }],
        category: 'geofence',
      },
      {
        name: 'Botanical Gardens',
        latitude: 11.4148,
        longitude: 76.7028,
        riskLevel: 'Low',
        hazardType: 'Heritage Garden / Low Risk',
        description: 'Government Botanical Garden established in 1848, spread over 55 acres with over 1,000 plant species including a fossilized tree trunk.',
        safeZone: { radius: 450, label: 'Garden Safe Zone', description: 'Well-maintained pathways with security guards and CCTV coverage.' },
        cautionZone: { radius: 600, label: 'Steep Garden Steps', description: 'Multi-level gardens with stone steps that can be slippery when wet.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Protected government garden with regular maintenance.' },
        safetyInstructions: 'Stay on pathways. Do not pluck flowers or plants. Be careful on wet stone steps during monsoon season.',
        nearbySafePoints: ['Garden Security Office (100m)', 'Ooty Bus Stand (500m)', 'Government Hospital (1.5 km)'],
        emergencyInformation: [{ label: 'Ooty Police', number: '0423-2443001' }, { label: 'Ambulance', number: '108' }],
        category: 'geofence',
      },
      {
        name: 'Doddabetta Peak',
        latitude: 11.4017,
        longitude: 76.7351,
        riskLevel: 'Moderate',
        hazardType: 'High-Altitude Peak / Weather Risk',
        description: 'Highest peak in Nilgiri Mountains at 2,637m. Telescope observation house and panoramic viewpoint. Prone to sudden fog and storms.',
        safeZone: { radius: 250, label: 'Observation House Zone', description: 'Concrete observation platform with telescope house and parking.' },
        cautionZone: { radius: 500, label: 'Road Curve Caution', description: 'Sharp hairpin bends on approach road with low visibility in fog.' },
        hazardZone: { radius: 700, label: 'Weather Exposure Zone', description: 'Sudden dense fog reduces visibility to near zero. Lightning risk during storms.' },
        safetyInstructions: 'Visit in morning for clear views. Drive slowly on curves. Do not stand on exposed rocks during thunderstorms. Carry warm clothing.',
        nearbySafePoints: ['Doddabetta Tea Museum (1 km)', 'Forest Department Office (3 km)', 'Ooty Town (10 km)'],
        emergencyInformation: [{ label: 'TNSDMA', number: '1070' }, { label: 'National Emergency', number: '112' }],
        category: 'caution',
      },
      {
        name: 'Nilgiri Mountain Railway',
        latitude: 11.4105,
        longitude: 76.6951,
        riskLevel: 'Low',
        hazardType: 'UNESCO Heritage Railway / Low Risk',
        description: 'UNESCO World Heritage steam/diesel rack railway connecting Mettupalayam to Ooty. One of the steepest rack railways in Asia.',
        safeZone: { radius: 300, label: 'Station Platform Safe Zone', description: 'Well-maintained heritage railway station with platform guards.' },
        cautionZone: { radius: 450, label: 'Track Crossing Caution', description: 'Level crossings near station. Do not walk on tracks.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Professionally operated heritage railway with safety protocols.' },
        safetyInstructions: 'Stay behind yellow lines on platforms. Do not lean out of windows during journey. Follow crew instructions at all times.',
        nearbySafePoints: ['Ooty Railway Station Master (50m)', 'Ooty Bus Stand (300m)', 'Police Station (800m)'],
        emergencyInformation: [{ label: 'Railway Emergency', number: '139' }, { label: 'Ooty Police', number: '0423-2443001' }],
        category: 'geofence',
      },
      {
        name: 'Pykara Falls & Lake',
        latitude: 11.4683,
        longitude: 76.5977,
        riskLevel: 'Moderate',
        hazardType: 'Waterfall / Flash Flood Risk',
        description: 'Scenic stepped waterfall and reservoir 20 km from Ooty. Popular for boating and forest walks. Flash flood risk during monsoon.',
        safeZone: { radius: 250, label: 'Boat House Safe Area', description: 'Managed boating facility with life guards and safety equipment.' },
        cautionZone: { radius: 500, label: 'Waterfall Approach Caution', description: 'Slippery rocks near falls. Strong water flow during monsoon.' },
        hazardZone: { radius: 700, label: 'Flash Flood Zone', description: 'Valley below falls prone to sudden flooding during heavy rain. Danger of being swept away.' },
        safetyInstructions: 'Do not swim near falls. Avoid area during heavy rain. Use authorized boating services only. Stay on marked viewing platforms.',
        nearbySafePoints: ['Pykara Forest Check Post (1 km)', 'TTDC Boathouse (500m)', 'Ooty Town (20 km)'],
        emergencyInformation: [{ label: 'DDMA Nilgiris', number: '1077' }, { label: 'National Emergency', number: '112' }],
        category: 'caution',
      },
      {
        name: 'Coonoor Landslide Zone – Burliar',
        latitude: 11.3396,
        longitude: 76.8012,
        riskLevel: 'High',
        hazardType: 'Active Landslide Zone',
        description: 'Steep tea estate slopes between Coonoor and Mettupalayam. History of catastrophic landslides during northeast monsoon. Soil saturation zone.',
        safeZone: { radius: 150, label: 'Highway Safe Segment', description: 'Reinforced road section with retaining walls.' },
        cautionZone: { radius: 400, label: 'Tea Estate Slope Caution', description: 'Saturated soil on steep slopes. Minor landslips common.' },
        hazardZone: { radius: 700, label: 'Critical Landslide Zone', description: 'Multiple documented landslides. Extremely dangerous during heavy rain. Road closures frequent.' },
        safetyInstructions: 'Do not stop vehicles on this stretch during rain. Avoid trekking on tea estate slopes during monsoon. Follow road closure advisories.',
        nearbySafePoints: ['Coonoor Town (8 km)', 'Wellington Army Hospital (10 km)', 'Mettupalayam Fire Station (15 km)'],
        emergencyInformation: [{ label: 'DDMA Nilgiris', number: '1077' }, { label: 'TNSDMA', number: '1070' }, { label: 'National Emergency', number: '112' }],
        category: 'hazard',
      },
      {
        name: 'Rose Garden & Thread Garden',
        latitude: 11.4234,
        longitude: 76.7067,
        riskLevel: 'Low',
        hazardType: 'Tourism Garden / Low Risk',
        description: 'Government Rose Garden with over 20,000 varieties of roses and the unique Thread Garden with handmade botanical replicas.',
        safeZone: { radius: 350, label: 'Garden Complex Safe Zone', description: 'Fenced garden with organized pathways and security.' },
        cautionZone: { radius: 500, label: 'Hillside Path Caution', description: 'Garden on sloped terrain. Steps can be uneven in sections.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Maintained government garden.' },
        safetyInstructions: 'Stay on marked paths. Do not touch or pluck roses. Watch for bees in flowering areas.',
        nearbySafePoints: ['Garden Security (100m)', 'Ooty Bus Stand (2 km)', 'Government Hospital (2.5 km)'],
        emergencyInformation: [{ label: 'Ooty Police', number: '0423-2443001' }, { label: 'Ambulance', number: '108' }],
        category: 'geofence',
      },
    ],
  },
  // ── DARJEELING, West Bengal ─────────────────────────────
  {
    key: 'darjeeling',
    label: 'Darjeeling, West Bengal',
    sources: [
      { label: 'West Bengal State Disaster Management Authority (WBSDMA)', url: 'https://wbdmd.gov.in/' },
      NATIONAL_LANDSLIDE_SOURCE,
      NATIONAL_FLOOD_SOURCE,
    ],
    emergencyContacts: [
      { label: 'National Emergency', number: '112', service: 'Police / Fire / Rescue' },
      { label: 'WBSDMA State Disaster Control Room', number: '1070', service: '24x7 State Emergency Operation' },
      { label: 'DDMA Darjeeling', number: '1077', service: 'District Disaster Control' },
      { label: 'Darjeeling Sadar Police', number: '0354-2254202', service: 'Town Police Station' },
      { label: 'Ambulance Triage', number: '108', service: 'Emergency Medical Services' },
      { label: 'Tourist Assistance Helpline', number: '1363', service: 'Ministry of Tourism' },
    ],
    locations: [
      {
        name: 'Tiger Hill Sunrise Point',
        latitude: 27.0137,
        longitude: 88.2807,
        riskLevel: 'Moderate',
        hazardType: 'High-Altitude Viewpoint / Weather Risk',
        description: 'Famous sunrise viewpoint at 2,590m for Kanchenjunga and Everest views. Extremely cold pre-dawn conditions with fog risk.',
        safeZone: { radius: 250, label: 'Observation Tower Zone', description: 'Covered observation tower with organized viewing platforms.' },
        cautionZone: { radius: 500, label: 'Dawn Road Caution', description: 'Dark, winding road before dawn. Steep edges without barriers in sections.' },
        hazardZone: { radius: 700, label: 'Fog & Black Ice Zone', description: 'Dense fog and black ice on road during winter mornings. Multiple accident spots.' },
        safetyInstructions: 'Dress in heavy woolens. Use vehicle with experienced local driver. Carry flashlight for pre-dawn walk. Watch for black ice.',
        nearbySafePoints: ['Tiger Hill Army Checkpoint (200m)', 'Ghoom Police Station (3 km)', 'Darjeeling District Hospital (11 km)'],
        emergencyInformation: [{ label: 'Darjeeling Police', number: '0354-2254202' }, { label: 'National Emergency', number: '112' }],
        category: 'caution',
      },
      {
        name: 'Mall Road & Chowrasta',
        latitude: 27.0440,
        longitude: 88.2636,
        riskLevel: 'Low',
        hazardType: 'Heritage Pedestrian Zone / Low Risk',
        description: 'Historic pedestrian plaza at the heart of Darjeeling. Meeting point of four roads with benches, views, and horse rides.',
        safeZone: { radius: 400, label: 'Chowrasta Safe Zone', description: 'Vehicle-free pedestrian plaza with police presence and medical aid.' },
        cautionZone: { radius: 550, label: 'Side Lane Caution', description: 'Narrow stepped lanes descending from Mall Road. Can be slippery.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Well-maintained heritage promenade with security.' },
        safetyInstructions: 'Watch for pony traffic at Chowrasta. Secure belongings. Use handrails on stepped lanes.',
        nearbySafePoints: ['Sadar Police Station (300m)', 'Darjeeling District Hospital (1 km)', 'Tourist Information Center (200m)'],
        emergencyInformation: [{ label: 'Darjeeling Police', number: '0354-2254202' }, { label: 'Ambulance', number: '108' }],
        category: 'geofence',
      },
      {
        name: 'Darjeeling Himalayan Railway (Toy Train)',
        latitude: 27.0430,
        longitude: 88.2619,
        riskLevel: 'Low',
        hazardType: 'UNESCO Heritage Railway / Low Risk',
        description: 'UNESCO World Heritage narrow-gauge steam railway from 1881. Iconic Batasia Loop and scenic mountain journey.',
        safeZone: { radius: 300, label: 'Station Safe Zone', description: 'Well-maintained heritage station with platform safety measures.' },
        cautionZone: { radius: 450, label: 'Track Crossing Caution', description: 'Railway runs through town streets. Watch for trains at crossings.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Professionally operated heritage railway.' },
        safetyInstructions: 'Stay behind safety lines. Do not lean out during journey. Follow crew instructions. Watch for train on town roads.',
        nearbySafePoints: ['Station Master Office (50m)', 'Darjeeling Mall Road (200m)', 'Sadar Police Station (500m)'],
        emergencyInformation: [{ label: 'Railway Emergency', number: '139' }, { label: 'Darjeeling Police', number: '0354-2254202' }],
        category: 'geofence',
      },
      {
        name: 'Batasia Loop & War Memorial',
        latitude: 27.0273,
        longitude: 88.2570,
        riskLevel: 'Low',
        hazardType: 'Heritage Viewpoint / Low Risk',
        description: 'Iconic railway loop with Gorkha War Memorial garden. Stunning Kanchenjunga panorama with manicured grounds.',
        safeZone: { radius: 350, label: 'Memorial Garden Zone', description: 'Maintained garden with walkways and viewing platforms.' },
        cautionZone: { radius: 500, label: 'Railway Track Caution', description: 'Active railway track passes through. Stay clear when train approaches.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Protected memorial site with safety measures.' },
        safetyInstructions: 'Stand clear when toy train approaches the loop. Do not walk on railway tracks. Follow posted signs.',
        nearbySafePoints: ['Batasia Loop Police Post (100m)', 'Ghoom Town (2 km)', 'Darjeeling Town (5 km)'],
        emergencyInformation: [{ label: 'Darjeeling Police', number: '0354-2254202' }, { label: 'National Emergency', number: '112' }],
        category: 'geofence',
      },
      {
        name: 'NH10 Landslide Zone – Teesta Valley',
        latitude: 27.0875,
        longitude: 88.4329,
        riskLevel: 'High',
        hazardType: 'Active Landslide Zone / River Erosion',
        description: 'Critical landslide-prone section along NH10 in Teesta River valley. Road carved into unstable hillside with river erosion undercutting.',
        safeZone: { radius: 150, label: 'Bridge Crossing Zone', description: 'Reinforced bridge sections with structural monitoring.' },
        cautionZone: { radius: 400, label: 'Valley Road Caution', description: 'Narrow road with falling debris. Single-lane sections.' },
        hazardZone: { radius: 800, label: 'Critical Landslide Corridor', description: 'Documented slide zone with fatalities. Road closures during monsoon. Rock avalanche risk.' },
        safetyInstructions: 'Do not stop vehicles in this zone. Follow convoy system during monsoon. Keep windows closed against debris. Check road status before travel.',
        nearbySafePoints: ['Teesta Bridge Army Post (1 km)', 'Kalimpong Town (20 km)', 'Siliguri (60 km)'],
        emergencyInformation: [{ label: 'WBSDMA', number: '1070' }, { label: 'DDMA Darjeeling', number: '1077' }, { label: 'National Emergency', number: '112' }],
        category: 'hazard',
      },
      {
        name: 'Happy Valley Tea Estate',
        latitude: 27.0501,
        longitude: 88.2717,
        riskLevel: 'Low',
        hazardType: 'Tea Plantation / Low Risk',
        description: 'Historic tea estate from 1854 offering guided plantation tours and tea tasting. One of few estates allowing tourist visits.',
        safeZone: { radius: 350, label: 'Factory & Tour Zone', description: 'Organized tour route with guides and safety measures.' },
        cautionZone: { radius: 500, label: 'Plantation Slope Caution', description: 'Terraced slopes can be slippery during rain. Uneven terrain.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Managed plantation with supervised tours.' },
        safetyInstructions: 'Follow guide on plantation walks. Wear proper footwear. Do not enter restricted processing areas.',
        nearbySafePoints: ['Tea Estate Office (100m)', 'Darjeeling Mall Road (1.5 km)', 'District Hospital (2 km)'],
        emergencyInformation: [{ label: 'Darjeeling Police', number: '0354-2254202' }, { label: 'Ambulance', number: '108' }],
        category: 'geofence',
      },
      {
        name: 'Sandakphu Trek Base – Manebhanjang',
        latitude: 26.9928,
        longitude: 88.1063,
        riskLevel: 'High',
        hazardType: 'High-Altitude Trek / Extreme Weather',
        description: 'Starting point for Sandakphu trek to 3,636m, the highest point in West Bengal. Extreme weather, remote terrain, no mobile connectivity.',
        safeZone: { radius: 200, label: 'Base Camp Zone', description: 'Manebhanjang village with basic facilities and trek registration.' },
        cautionZone: { radius: 500, label: 'Forest Trail Caution', description: 'Dense rhododendron forest with leeches, steep gradients, and stream crossings.' },
        hazardZone: { radius: 800, label: 'Extreme Weather Zone', description: 'Sub-zero temperatures, blizzard conditions possible. No rescue infrastructure above treeline.' },
        safetyInstructions: 'Register with local authorities before trek. Hire certified guide mandatory. Carry cold-weather gear, first-aid kit, and enough food/water. Do not trek in monsoon.',
        nearbySafePoints: ['Manebhanjang Police Post (200m)', 'Tonglu Trekkers Hut (10 km trek)', 'Darjeeling Town (28 km)'],
        emergencyInformation: [{ label: 'WBSDMA', number: '1070' }, { label: 'National Emergency', number: '112' }, { label: 'Darjeeling Police', number: '0354-2254202' }],
        category: 'hazard',
      },
      {
        name: 'Peace Pagoda (Japanese Temple)',
        latitude: 27.0354,
        longitude: 88.2502,
        riskLevel: 'Low',
        hazardType: 'Heritage Temple / Low Risk',
        description: 'Buddhist Peace Pagoda built by Japanese monks in 2010. Offers serene meditation space with Kanchenjunga views.',
        safeZone: { radius: 300, label: 'Temple Complex Zone', description: 'Well-maintained temple grounds with proper access road.' },
        cautionZone: { radius: 450, label: 'Approach Road Caution', description: 'Narrow access road with steep curves. Limited parking.' },
        hazardZone: { radius: 0, label: 'No Active Hazard', description: 'Peaceful temple site with regular maintenance.' },
        safetyInstructions: 'Remove shoes before entering temple. Maintain silence in meditation areas. Drive slowly on approach road.',
        nearbySafePoints: ['Japanese Temple Office (50m)', 'Darjeeling Town (3 km)', 'District Hospital (4 km)'],
        emergencyInformation: [{ label: 'Darjeeling Police', number: '0354-2254202' }, { label: 'National Emergency', number: '112' }],
        category: 'geofence',
      },
    ],
  },
];

const RISK_TO_ZONE = { Low: 'safe', Moderate: 'caution', High: 'danger' };
const RISK_TO_ALERT = { Low: 'info', Moderate: 'warning', High: 'critical' };

const buildZone = (destination, loc, order) => {
  const catalogKey = `${destination.key}-${String(order + 1).padStart(2, '0')}`;
  const source = destination.sources.find((entry) =>
    loc.hazardType.toLowerCase().includes('landslide') ||
    loc.hazardType.toLowerCase().includes('flood') ||
    loc.hazardType.toLowerCase().includes('river')
  ) || destination.sources[0];

  const primaryRadius = loc.riskLevel === 'High'
    ? (loc.hazardZone?.radius || 500)
    : loc.riskLevel === 'Moderate'
      ? (loc.cautionZone?.radius || 400)
      : (loc.safeZone?.radius || 350);

  return {
    name: loc.name,
    description: loc.description,
    type: RISK_TO_ZONE[loc.riskLevel] || 'safe',
    category: loc.category || 'geofence',
    center: { type: 'Point', coordinates: [loc.longitude, loc.latitude] },
    radius: primaryRadius,
    alertLevel: RISK_TO_ALERT[loc.riskLevel] || 'info',
    alertMessage: loc.description,
    isActive: true,
    linkedDestinations: [],
    metadata: {
      safetyCatalog: true,
      safetyCatalogKey: catalogKey,
      safetyDestination: destination.key,
      safetyDestinationLabel: destination.label,
      safetyOrder: order,
      latitude: loc.latitude,
      longitude: loc.longitude,
      hazardType: loc.hazardType,
      riskLevel: loc.riskLevel,
      safeZone: loc.safeZone,
      cautionZone: loc.cautionZone,
      hazardZone: loc.hazardZone,
      safetyInstructions: loc.safetyInstructions,
      nearbySafePoints: loc.nearbySafePoints,
      emergencyInformation: loc.emergencyInformation || destination.emergencyContacts,
      destinationEmergencyContacts: destination.emergencyContacts,
      sourceLabel: source.label,
      sourceUrl: source.url,
      sourceNote: 'Official disaster management and NDMA/SDMA guidelines provide preparedness principles. Zone boundaries are approximate geospatial planning aids.',
      boundaryAccuracy: 'approximate',
    },
  };
};

const getSafetyDestinationOptions = () => DESTINATIONS.map(({ key, label }) => ({ key, label }));

const seedTouristSafetyZones = async () => {
  const operations = DESTINATIONS.flatMap((destination) =>
    destination.locations.map((loc, order) => {
      const zone = buildZone(destination, loc, order);
      return {
        updateOne: {
          filter: { 'metadata.safetyCatalogKey': zone.metadata.safetyCatalogKey },
          update: { $set: zone },
          upsert: true,
        },
      };
    })
  );

  const result = await Zone.bulkWrite(operations, { ordered: false });
  console.log(`[Safety Zones] Ensured ${operations.length} tourist safety map locations (${result.upsertedCount} inserted, ${result.modifiedCount} updated).`);
  return operations.length;
};

module.exports = { seedTouristSafetyZones, getSafetyDestinationOptions, DESTINATIONS };
